### ISSUE TITLE
Vulkan not working on AMD and Intel GPUs

### ISSUE THREAD

**Issue by Waddlen** [canonical/steam-snap#101]
**Describe the bug**
Vulkan games fail to launch. This includes many native games and virtually all Proton games. This does NOT occur with Flatpak Steam. The usual errors in the logs are an inability to access `/usr/share/libdrm/amdgpu.ids` and a Vulkan error, unable to use `VK_KHR_surface`

**To Reproduce**

1. Open Steam library
2. Launch a Vulkan-enabled game, for example:

- The Talos Principle (native)
- VVVVVV (Force the use of Proton 7.0-5 instead of native)

3. Game immediately crashes

**Expected behavior**
Game launches

**Environment**
```
os_release: 
    name:               "Ubuntu"
    version:            "22.10 (Kinetic Kudu)"
snap_info: 
    steam_revision:     97
    snapd_revision:     17883
lspci: 
    03:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c3)
glxinfo: 
    gpu:                NAVI21 (navi21, LLVM 15.0.4, DRM 3.47, 5.19.0-26-generic)
    gpu_version:        4.6 (Core Profile) Mesa 22.3.0 - kisak-mesa PPA
lscpu: 
    model_name:         AMD Ryzen 7 7700X 8-Core Processor
```

**Logs**
[Running snap steam from terminal](https://github.com/canonical/steam-snap/files/10292510/steam.log)
[Proton log for VVVVVV](https://github.com/canonical/steam-snap/files/10292511/steam-70300.log)

**Additional Context**
I suspect this is the root issue for:
https://github.com/canonical/steam-snap/issues/26
https://github.com/canonical/steam-snap/issues/37
Some users in https://github.com/canonical/steam-snap/issues/49

**Comment by Waddlen** [comment]
Running `vulkaninfo`, it attempts to read from a non-existent directory `/snap/steam/97/usr/share/vulkan/`
```
mneidig@matt-pc:~$ snap run --shell steam
mneidig@matt-pc:/home/mneidig$ vulkaninfo
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file /snap/steam/97/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file /snap/steam/97/usr/share/vulkan/icd.d/intel_icd.x86_64.json
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:649:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
mneidig@matt-pc:/home/mneidig$ 
```

I unpacked steam.snap and copied my local `/usr/share/vulkan/` to `~/squashfs-root/usr/share/vulkan/` , then `snap try squashfs-root/`

Closer, but still an error:
```
mneidig@matt-pc:~$ snap run --shell steam
mneidig@matt-pc:/home/mneidig$ vulkaninfo
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json
ERROR: [Loader Message] Code 0 : /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so: file too short
ERROR: [Loader Message] Code 0 : /usr/lib/x86_64-linux-gnu/libvulkan_intel.so: file too short
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:649:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
mneidig@matt-pc:/home/mneidig$ exit
exit
```
It seems `/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so` was a 0 byte file. I copied my local copy of the file into the snap:
```
sudo cp /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so ~/squashfs-root/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
...
sudo chown -R mneidig libvulkan_radeon.so
...
snap try squashfs-root/
```
Now `vkcube`, `vulkaninfo` work correctly! The Talos Principle also launches. 

VVVVVV through Proton is still crashing, but it seems to be a separate issue.

**Comment by ashuntu** [comment]
Strange, on my system `libvulkan_radeon.so` is the correct one in the Snap, `/usr/share/vulkan` also exists and `vulkaninfo` works fine. However, I have an Intel/NVIDIA system.

I know you've found a workaround already it seems, but have you also tried using [`PROTON_USE_WINED3D=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) in the launch options of the Proton games?

**Comment by Waddlen** [comment]
> Strange, on my system `libvulkan_radeon.so` is the correct one in the Snap, `/usr/share/vulkan` also exists and `vulkaninfo` works fine. However, I have an Intel/NVIDIA system.

I have completely removed the steam snap with `sudo snap remove --purge steam` and reinstalled "Steam (Early Access)" edge from the Ubuntu Software GUI. There is no `/snap/steam/current/usr/share/vulkan/` directory and `/snap/steam/current/usr/lib/x86_64-linux-gnu/` does not contain a `libvulkan_radeon.so` file.

**Comment by kenvandine** [comment]
It's provided as a layout in the snap, so you won't find it by listing from outside the snap runtime.  

```
snap run --shell steam
ls -l $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
-rwxr-xr-x 1 root root 0 Jan  5 11:51 /snap/steam/98/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
```

**Comment by Waddlen** [comment]
> It's provided as a layout in the snap, so you won't find it by listing from outside the snap runtime.
> 
> ```
> snap run --shell steam
> ls -l $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
> -rwxr-xr-x 1 root root 0 Jan  5 11:51 /snap/steam/98/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
> ```

I can see it with your command. However, you see `root root 0`? I believe that indicates the file is 0 bytes long. When I run that command on my local non-snap file, I get approx 8.7MB (`root root 8690992`)
```
mneidig@matt-pc:~$ ls -l /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so 
-rw-r--r-- 1 root root 8690992 Dec 29 20:18 /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
```

Inside my fresh Steam Snap edge, `vulkaninfo`, `vkcube`, "The Talos Principle" are all still broken:

```
mneidig@matt-pc:~$ snap run --shell steam
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

mneidig@matt-pc:/home/mneidig$ ls -l $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
-rwxr-xr-x 1 root root 0 Jan  5 11:55 /snap/steam/98/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
mneidig@matt-pc:/home/mneidig$ vulkaninfo
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file /snap/steam/98/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file /snap/steam/98/usr/share/vulkan/icd.d/intel_icd.x86_64.json
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:649:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
mneidig@matt-pc:/home/mneidig$ vkcube
vkEnumerateInstanceExtensionProperties failed to find the VK_KHR_surface extension.

Do you have a compatible Vulkan installable client driver (ICD) installed?
Please look at the Getting Started guide for additional information.

mneidig@matt-pc:/home/mneidig$ 
```

**Comment by ashuntu** [comment]
When I remove my Steam install and reinstall on edge, I also get a 0 byte file. Refreshing to the beta branch creates the file correctly. My assumption is an issue with the `gaming-graphics-core22` Snap

**Comment by Waddlen** [comment]
> @Waddlen not sure if you've tried, but try on the beta branch instead (`snap refresh steam --beta`)

👍 `vulkaninfo`, `vkcube`, "The Talos Principle" working on beta branch

**Comment by Waddlen** [comment]
I confirm this is fixed on the edge branch

**Comment by kenvandine** [comment]
> I confirm this is fixed on the edge branch

Excellent!  Thanks for testing.
