### ISSUE TITLE
Tray icon displays as corrupt/missing

### ISSUE THREAD

**Issue by thoughton** [canonical/steam-snap#102]
Tray icon displays as corrupt/missing:

![image](https://user-images.githubusercontent.com/38389/210136334-663485e2-f2a9-4400-9473-c00f3ddd0392.png)

This worked correctly when using a previous installation from the apt repository.

As can also be seen in the above screenshot, other application icons do still appear correctly.

A bit of system info (not sure how relevant):
```
OS: Ubuntu 22.10 x86_64 
Kernel: 5.19.0-23-generic 
Resolution: 1920x1080 
DE: GNOME 43.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Yaru [GTK2/3] 
```

Please let me know if there's any other info that could help.

Thanks!

**Comment by ashuntu** [comment]
Is this still an issue with the latest version of the Snap?

**Comment by thoughton** [comment]
@ashuntu it's been ok recently. Can't say for certain when it started working! I'll close this now. Thanks for checking!
