### ISSUE TITLE
Small UI on HiDPI screen

### ISSUE THREAD

**Issue by Lukewh** [canonical/steam-snap#11]
Fractional scaling at 150% on 22.04

![image](https://user-images.githubusercontent.com/479384/166455227-1514f2e2-f211-4541-b607-5d2054812e7f.png)

**Comment by ashuntu** [comment]
Initial modals like the one screenshotted as well as my mouse cursor is small, 4k screen. Might be related to #10.

**Comment by ashuntu** [comment]
The small cursor issue was solved in #34, see issue #10.

As of the most recent build, I can't reproduce any issues with modals on my HiDPI screen and the Steam snap. @Lukewh, are you still experiencing scaling issues or can this issue be closed?

[I've also added a section in the README about HiDPI screens.](https://github.com/canonical/steam-snap#hidpi=)

**Comment by ashuntu** [comment]
Assuming this issue is resolved, feel free to reopen if it is still a problem.
