### ISSUE TITLE
install instructions invalid install using  snap install --beta steam returns STEAM_ZENITY: unbound variable

### ISSUE THREAD

**Issue by NicTanghe** [canonical/steam-snap#110]
The only thing snap allows me to install is  ```snap install --beta steam```

Running this opens steam wich self updates and then throws.

```
steam.sh[7325]: STEAM_RUNTIME is enabled automatically
/home/nanghe/snap/steam/common/.local/share/Steam/steam.sh: line 310: STEAM_ZENITY: unbound variable

```

**Comment by ashuntu** [comment]
I'm assuming this a fresh install? Could you share your Linux distribution and some system info (you can use `snap run steam.report --no-submit` if it works)?

**Comment by NicTanghe** [comment]
Hello I`ve decited to use flatpak instead and wil not continieu troubleshooting this.
(I tend to avoid conanical anyhow)
