### ISSUE TITLE
Steam client detects GPU as Mesa llvmpipe instead of discrete Nvidia driver

### ISSUE THREAD

**Issue by ZoopOTheGoop** [canonical/steam-snap#127]
This is from Steam's system info:
```
Video Card:
    Driver:  Mesa llvmpipe (LLVM 15.0.6, 256 bits)
    Driver Version:  4.5 (Compatibility Profile) Mesa 23.1.0-devel (git-e2c67ed 2023-03-02 jammy-oibaf-ppa)
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1e87
    Revision Not Detected
    Number of Monitors:  3
    Number of Video Cards Not Detected
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 7680 x 1440
    Primary Display Size: 23.54" x 13.23" (26.97" diag)
                                            59.8cm x 33.6cm (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6720 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
```

llvmpipe is a CPU software renderer for if no GPU is detected

Interestingly, steam report *does* detect it
```
lspci: error while loading shared libraries: libpci.so.3: cannot open shared object file: No such file or directory
os_release: 
    name:               "Ubuntu"
    version:            "22.10 (Kinetic Kudu)"
snap_info: 
    steam_revision:     124
    snapd_revision:     x15
lspci: 
glxinfo: 
    gpu:                NVIDIA GeForce RTX 2080/PCIe/SSE2
    gpu_version:        4.6.0 NVIDIA 525.78.01
lscpu: 
    model_name:         AMD Ryzen 9 5900X 12-Core Processor
xdg_current_desktop:    KDE
desktop_session:        plasma
```

It seems likely that the `lspci` issue is the culprit. Did we somehow remove that by accident?

**Comment by ZoopOTheGoop** [comment]
`pciutils` is on line 266 of the snapcraft.yaml

I'm wondering if maybe it's also in `gaming-graphics-core22` and the cleanup phase is somehow nuking it? Don't want to do work on the weekend so I'll leave this sit, I was just gonna play a game and got very confused.

**Comment by ashuntu** [comment]
You know this, but for the sake of posterity: this *should* be temporarily resolved by running `sudo /usr/lib/snapd/snap-discard-ns steam`, and should be permanently fixed by this snapd PR: https://github.com/snapcore/snapd/pull/12541

**Comment by ashuntu** [comment]
Worth trying this again with updated snapd and steam @ZoopOTheGoop.

**Comment by ZoopOTheGoop** [comment]
it works on edge/zygmunt's branch that good enough @ashuntu?

**Comment by ZoopOTheGoop** [comment]
tbh I think a workaround from simon fixed this ages ago

**Comment by ashuntu** [comment]
Probably, it's been a while. If it works fine feel free to close.
