### ISSUE TITLE
Add ttf-mscorefonts

### ISSUE THREAD

**Issue by jor1196** [canonical/steam-snap#128]
In this issue I see that the game requires this package of fonts

https://github.com/canonical/steam-snap/issues/119

**Comment by ashuntu** [comment]
Not having these fonts shouldn't impact the game's functionality. Additionally, we will not be able to include these fonts with the Snap for the foreseeable future because they require the user to accept a [EULA](https://en.wikipedia.org/wiki/End-user_license_agreement).
