### ISSUE TITLE
Steam beta steamwebhelper crashes, because it cannot launch its sandbox helper

### ISSUE THREAD

**Issue by smcv** [canonical/steam-snap#16]
To reproduce:

* `sudo snap refresh --beta snapd`
* `sudo snap install --beta steam`
* `snap run steam`
* Log in to an account
* Steam → Settings → Account → Beta participation → Change → Steam Beta Update
* Let Steam restart when prompted
* Look at Store, Library, etc.

Expected result: Store, Library, etc. still work.

Actual result: `steamwebhelper` process crashes repeatedly, content area remains blank.

Workaround: Run as `snap run steam -no-cef-sandbox` instead.

**Comment by smcv** [comment]
If there is an official way for an application to detect that it is running in a Snap environment, Steam could work around this by disabling the `steamwebhelper` sandbox helper, as it already does when presence of `/.flatpak-info` indicates that it's running under Flatpak.

Unfortunately, the Snap app's AppArmor profile doesn't seem to allow reading `/proc/self/attr/current` or `/proc/self/attr/apparmor/current` to check for `snap.*`, and Snap doesn't seem to implement [`/run/host/container-manager`](https://systemd.io/CONTAINER_INTERFACE/).

Are the `$SNAP_*` environment variables intended to be "API"?

**Comment by kenvandine** [comment]
@smcv thanks for this info!  Neither @ashtoncano nor I can actually reproduce this crash, but in looking closer at it I don't see a compelling reason for the sandboxing inside the snap environment.  Do you see any issue with us just adding --no-sandbox?  

The most common pattern for determining if we're running as a snap is looking for the existence of $SNAP, we use that the same as you would for checking for the existence of .flatpak-info

**Comment by DenX** [comment]
With the recent update Steam pushed I see the same behavior. Content windows are blank.
The workaround helps.
