### ISSUE TITLE
Restart for update button does quit Steam but does note restart it

### ISSUE THREAD

**Issue by lightrush** [canonical/steam-snap#162]
**Describe the bug**

I got the standard Steam update popup prompting me to restart it. I clicked the button. Steam closed but it did not restart.

**To Reproduce**

1. Get Restart for update dialog to show
2. Click on Restart button

**Expected behavior**
Steam quits, then restarts on its own.

**Environment**

```
lspci: error while loading shared libraries: libpci.so.3: cannot open shared object file: No such file or directory
os_release: 
    name:               "Ubuntu"
    version:            "22.04.2 LTS (Jammy Jellyfish)"
snap_info: 
    steam_revision:     124
    snapd_revision:     
lspci: 
glxinfo: 
    gpu:                NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
    gpu_version:        4.6.0 NVIDIA 525.85.05
lscpu: 
    model_name:         AMD Ryzen 7 1800X Eight-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

**Comment by ashuntu** [comment]
This *seems* to be working for me, I'll close this for now unless it comes up again or is still an issue.
