### ISSUE TITLE
Steam's diagnostic tool fails because basic CLI tools cannot be run

### ISSUE THREAD

**Issue by smcv** [canonical/steam-snap#17]
To reproduce:

* `sudo snap refresh --beta snapd`
* `sudo snap install --beta steam`
* `snap run steam` (possibly with `-no-cef-sandbox` to work around #16)
* Log in to an account
* Help -> System Information
* Wait

Expected result: several large blobs of JSON describing the environment Steam finds itself running in, which is used by Valve developers to debug compatibility issues. They don't indicate any major problems.

Actual result: The diagnostic tool fails to detect presence/compatibility of any shared libraries. Graphics-stack smoke-tests all report `Failed to execute child process "timeout" (Permission denied)`.

In the Journal, this is reported like so:

```
audit[12345]: AVC apparmor="DENIED" operation="exec" profile="snap.steam.steam" name="/usr/bin/timeout" pid=12345 comm="i386-linux-gnu" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
```

This seems to be happening because the diagnostic tool wraps diagnostic subprocesses in coreutils `timeout(1)`, to guard against faulty libraries or graphics drivers that might deadlock or otherwise hang indefinitely.

I would expect it to be possible to run basic CLI tools like the ones from `coreutils` without interference from AppArmor, and without raising or lowering privileges; I think that's `/usr/bin/timeout rmix`, if I'm remembering my AppArmor syntax correctly.

**Comment by ashuntu** [comment]
This seems to have been resolved since opening (I'm able to get system information and run the runtime diagnostics with no errors), closing.
