### ISSUE TITLE
Steam Play section is hidden in Settings for navigation with mouse scroll button and scroll bars too

### ISSUE THREAD

**Issue by sati-mutwa** [canonical/steam-snap#174]
Going to upper left corner Steam menu, from there to Settings and there comes the indicated option list as shown in attachment. You can't get to Steam Play section which is under "Shader Pre-Caching" with mouse. Not with using the scroll bar or the scroll button on mouse. You have to go on top of that Shader Pre-Caching one, and from there press arrow down to reach the Steam Play section.

Users looking to enable Proton will be confused and many not finding the place, using Steam Snap due to this bug.
![Screenshot from 2023-03-20 16-37-32](https://user-images.githubusercontent.com/128394622/226374849-28c82af8-6b88-4113-a607-f62f15941d0d.png)
![Screenshot from 2023-03-20 16-42-15](https://user-images.githubusercontent.com/128394622/226374891-c8cab49a-3a81-45ea-b8a9-4e0a2b5d09ae.png)

**Comment by ashuntu** [comment]
That font issue has since been fixed, and the Steam UI has been updated. Could you verify if this is still an issue? I'm unable to reproduce it anywhere else.

**Comment by ashuntu** [comment]
Due to no response, I'm going to close this for now. Feel free to reopen if its still an issue.
