### ISSUE TITLE
/usr/share/libdrm/amdgpu.ids: No such file or directory

### ISSUE THREAD

**Issue by jor1196** [canonical/steam-snap#176]
I have this problem, maybe it's a lack of access, it also happens with other snaps. 

https://forum.snapcraft.io/t/apps-from-snap-cannot-access-usr-share-libdrm-amdgpu-ids/31672

This could work. 
https://github.com/altair-graphql/altair/issues/1969#issuecomment-1240675999

**Comment by kaincenteno** [comment]
can confirm i see the same on me end, have seen it with other snaps 

```/usr/share/libdrm/amdgpu.ids: No such file or directory```
