### ISSUE TITLE
The steam UI is just black

### ISSUE THREAD

**Issue by d43dm4n** [canonical/steam-snap#18]
![Screenshot from 2022-05-15 10-33-27](https://user-images.githubusercontent.com/90857003/168464162-783ddce7-cc8d-4bb2-8a20-f99fdb5c3158.png)

It is pretty unusable this way. I have no clue what could I try to solve this

**Comment by Operativ** [comment]
I can confirm, the same situation on a freshly installed Ubuntu 22.04.

Selecting Steam beta opt-in and opt-out does not change anything. Checking for updates does not resolve this.

This is on the --beta channel.

**Comment by DenX** [comment]
Steam has rolled out the update which is causing the blank windows in the Steam snap. The workaround has been posted in #16.

**Comment by ashtoncano** [comment]
@d43dm4n Revision 17 (newest as of now) in Beta should disable the sandbox (#16) for the webhelper, give that a try and see if it works.

**Comment by ashuntu** [comment]
I'm going to close this issue since it should be resolved. If it isn't feel free to re-open.
