### ISSUE TITLE
Nvidia Prime requires additional command to use discrete GPU

### ISSUE THREAD

**Issue by Cardiacman13** [canonical/steam-snap#195]
Description: When using the Steam Snap on Ubuntu with Nvidia Prime on "on demand" mode games do not launch using the discrete GPU unless the additional command "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia %command%" is used.

Steps to reproduce:

Install Ubuntu and the Nvidia drivers.
Install the Steam Snap and launch it.
Launch a game from the Steam library :

Expected results:
The game should launch using the Nvidia discrete GPU automatically.

Actual results:
The game launches using the integrated GPU instead of the Nvidia discrete GPU.

Workaround:
To use the Nvidia discrete GPU, i need to use the additional command "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia %command%" in the launch options of the game.

Proposed solution:
It is recommended that the Steam Snap be updated to automatically use the Nvidia discrete GPU when it is enabled through Nvidia Prime. This will eliminate the need for the additional command and provide a better user experience.

Thank you for your attention to this matter. Let me know if you need any further information.

**Comment by Synaxis** [comment]
confirmed here

**Comment by ErickLandowski** [comment]
I have the same problem. Nvidia RTX 3050 Mobile here.

**Comment by AussieAnon** [comment]
Same issue with Intel Xe/NVIDIA RTX 4060

**Comment by Cardiacman13** [comment]
Has anyone tried it [since](https://www.gamingonlinux.com/2023/11/canonical-detail-a-whole-lot-of-steam-snap-improvements/)? I left Ubuntu so I can't test it, but I would like to know if there's any progress, to find out if I can recommend the SNAP to my gamer friends on Ubuntu.

**Comment by Cardiacman13** [comment]
I just installed Ubuntu specifically to test if the issue is resolved with the edge version of the Steam snap. I can go back to Arch now.
