### ISSUE TITLE
Input of non-English characters doesn't work in Steam overlay

### ISSUE THREAD

**Issue by DefaultX-od** [canonical/steam-snap#21]
Info:
Ubuntu 20.04.4
Snapd version: 2.56+git890.gadf1d93, from edge channel
Steam Snap version: 1.0.0.74, from edge channel

Problem:
Can't type in the steam client or chat when keyboard layout is not English. Tested it with Italian and Russian.

**Comment by DefaultX-od** [comment]
When running from terminal, I get this error message:

> WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.

**Comment by jhenstridge** [comment]
We don't have compiled locales available within the snap sandbox. I suspect adding `locales-all` to stage-packages will solve the problem.

**Comment by DefaultX-od** [comment]
Reopening as #86 broke it again.

**Comment by ashuntu** [comment]
@DefaultX-od can you confirm the details of this again? Are you experiencing the exact same issue or is it manifesting in other ways/with different logs?

**Comment by DefaultX-od** [comment]
It is the exact same situation.

**Comment by DefaultX-od** [comment]
The only difference is that I can type in Russian in the big picture mode, I'm not sure was this the case before this issue was closed.

**Comment by DefaultX-od** [comment]
Maybe this could help to understand the issue better?

```
defaultx-od@defaultxod-Vostro-14-5410:~$ locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
warning: The LOCPATH variable is set to "/snap/steam/93/usr/lib/locale"
C
C.utf8
POSIX
```
This I got from running `locale -a` within steam shell

**Comment by DefaultX-od** [comment]
Could this issue be related to the base change? I'm asking because I just built it from @ashuntu fix-locale branch, and it works! Looking at the contents of the files, I do not notice anything suspicious between @ashuntu fix-locale branch and main. I'm going to be honest here, I didn't use it for a long time, as I got frustrated with GTA IV not working, so I'm sorry if I didn't report it at the time.

**Comment by DefaultX-od** [comment]
Running `locale -a` from steam shell with snap built from fix-locale branch shows this:
```
defaultx-od@defaultxod-MS-7971:/home/defaultx-od$ locale -a
C
C.UTF-8
POSIX
```

**Comment by kenvandine** [comment]
@DefaultX-od can you please test what's in the beta channel?

**Comment by DefaultX-od** [comment]
@kenvandine same thing on the beta channel. Beta channel also using core 22.

**Comment by kenvandine** [comment]
I don't think the base change is related, we haven't seen this with other snaps using core22.

**Comment by DefaultX-od** [comment]
What could possibly be the source of this issue, then?

**Comment by kenvandine** [comment]
It's probably locale related, but I need to spend some time bisecting changes.

**Comment by DefaultX-od** [comment]
The Steam beta update fixes this, now we need to wait for it to become stable, and then this issue can be closed.

**Comment by ashuntu** [comment]
This is resolved in stable.

Input in the overlay still does not work at the moment.
