### ISSUE TITLE
CPU governor error in feral games

### ISSUE THREAD

**Issue by amardhruva** [canonical/steam-snap#218]
**Describe the bug**
Gamemode enabled games such as ferals titles (Total war warhammer 3, Shadow of the Tomb Raider) use gamemode to put the CPU governor into performance mode. This works on native steam but does not work in snap causing low FPS.

**To Reproduce**
Install one of the games listed here

-DiRT 4
-Rise of the Tomb Raider
-Shadow of the Tomb Raider
-Total War Saga: Thrones of Britannia
-Total War: ROME REMASTERED
-Total War: Three Kingdoms
-Total War: WARHAMMER II
-Total War: WARHAMMER III

Run the Game while on cpu governor not in high-performance.

Game shows warning that 

**Expected behavior**
Game switches governor to high performance while running

**Screenshots**

![linux bug 2a](https://user-images.githubusercontent.com/7582063/234671651-a669f0e1-083e-4768-8450-94cc70f57776.png)
![linux bug 2b](https://user-images.githubusercontent.com/7582063/234671670-6d66d81c-581c-40d6-8155-fd5cd70e0ca0.png)

**Environment**

`snap run steam.report`

```
os_release: 
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info: 
    steam_revision:     136
    snapd_revision:     18933
lspci: 
    00:02.0:            Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)
    01:00.0:            NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
glxinfo: 
    gpu:                Mesa Intel(R) UHD Graphics (CML GT2)
    gpu_version:        4.6 (Core Profile) Mesa 23.0.2 - kisak-mesa PPA
lscpu: 
    model_name:         Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
xdg_current_desktop:    KDE
desktop_session:        plasmawayland

Opening web browser...
/snap/steam/136/usr/bin/xdg-open: 607: kde-open5: not found

```

**Comment by ashuntu** [comment]
GameMode support is being worked on, see https://github.com/canonical/steam-snap/issues/42.
