### ISSUE TITLE
Qt plugin wayland-egl not included

### ISSUE THREAD

**Issue by kenvandine** [canonical/steam-snap#22]
Civilization VI requires Qt platform plugin wayland-egl

GameAction [AppID 289070, ActionID 7] : LaunchApp changed task to Completed with ""
   FATAL: This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: xcb.

**Comment by kenvandine** [comment]
This works with wayland disabled, which we probably want to do anyway

**Comment by jor1196** [comment]
How to enable Wayland?
