### ISSUE TITLE
Update the `yaru-for-steam` to v0.38

### ISSUE THREAD

**Issue by soumyaDghosh** [canonical/steam-snap#223]
**Is your feature request related to a problem? Please describe.**

The current yaru-for-steam is atleast 4 versions behind of the upstream. Kindly update it. The current version doesn't looks good with Gnome 44.

**Describe the solution you'd like**
Sync the fork with the upstream and make the necessary changes in the pngs, svgs and css needed for yaru color pallette.

**Describe alternatives you've considered**

A revamp in the ui can also be done.

**Comment by ashuntu** [comment]
This isn't a great place for this issue, but I understand the [yaru-for-steam](https://github.com/ubuntu/yaru-for-steam) repo doesn't have an issue tracker. We will contact the maintainer of yaru-for-steam about this.

**Comment by kenvandine** [comment]
Upstream yaru-for-steam has updated, it will get picked up in the next build of the steam snap
