### ISSUE TITLE
Replace wiki with editable docs

### ISSUE THREAD

**Issue by techtonik** [canonical/steam-snap#240]
**Describe the bug**

The wiki can not be edited, and its not helpful. There are many problems.
 
### 1. Neither `README.md` nor `wiki` contain up to date installation instructions

[Wiki](https://github.com/canonical/steam-snap/wiki#install) recommends installing outdated beta snap.
```
snap install steam --beta
```
```
❯ snap info steam
name:      steam
summary:   Launcher for the Steam software distribution service
publisher: Canonical✓
store-url: https://snapcraft.io/steam
contact:   https://github.com/canonical/steam-snap
license:   unset
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
commands:
  - steam.glxgears
  - steam.glxinfo
  - steam.report
  - steam
  - steam.test
  - steam.vkcube
  - steam.vulkaninfo
snap-id:      NeoQngJVBf2wKC48bxnF2xqmfEFGdVnx
tracking:     latest/stable
refresh-date: today at 08:43 +03
channels:
  latest/stable:    1.0.0.76 2023-06-01 (146) 188MB -
  latest/candidate: 1.0.0.76 2023-06-01 (150) 191MB -
  latest/beta:      1.0.0.75 2022-12-05  (83) 388MB -
  latest/edge:      1.0.0.76 2023-05-31 (150) 191MB -
installed:          1.0.0.76            (146) 188MB -
```
I would merge it with README's "installing from source".

### 2. Installation instructions are incomplete

After refreshing snap, `steam.report` doesn't work.
```
❯ sudo snap refresh steam --stable
steam 1.0.0.76 from Canonical✓ refreshed
```
```
❯ snap run steam.report
This script relies on the system-observe Snap plug.
Outside of the snap, run `snap connect steam:system-observe`.
```
Looks like there are many disconnected slots.
```
❯ snap connections steam
Interface               Plug                          Slot                                Notes
audio-playback          steam:audio-playback          :audio-playback                     -
audio-record            steam:audio-record            -                                   -
bluez                   steam:bluez                   -                                   -
content[gaming-mesa]    steam:gaming-mesa             gaming-graphics-core22:gaming-mesa  -
content[gtk-3-themes]   steam:gtk-3-themes            gtk-common-themes:gtk-3-themes      -
content[icon-themes]    steam:icon-themes             gtk-common-themes:icon-themes       -
content[sound-themes]   steam:sound-themes            gtk-common-themes:sound-themes      -
desktop                 steam:desktop                 :desktop                            -
desktop-legacy          steam:desktop-legacy          :desktop-legacy                     -
fuse-support            steam:fuse-support            -                                   -
gsettings               steam:gsettings               :gsettings                          -
hardware-observe        steam:hardware-observe        -                                   -
home                    steam:home                    :home                               -
joystick                steam:joystick                :joystick                           -
mount-observe           steam:mount-observe           -                                   -
network                 steam:network                 :network                            -
network-control         steam:network-control         -                                   -
opengl                  steam:opengl                  :opengl                             -
personal-files          steam:dot-local-share-steam   -                                   -
process-control         steam:process-control         -                                   -
removable-media         steam:removable-media         :removable-media                    -
screen-inhibit-control  steam:screen-inhibit-control  :screen-inhibit-control             -
shared-memory           steam:shmem                   :shared-memory                      -
steam-support           steam:steam-support           :steam-support                      -
system-observe          steam:system-observe          -                                   -
uinput                  steam:uinput                  :uinput                             -
upower-observe          steam:upower-observe          :upower-observe                     -
wayland                 steam:wayland                 :wayland                            -
x11                     steam:x11                     :x11                                -
```

### 3. Enabling Proton should be docs

Proton titles don't work, probably because it requires `hardware-observe` from above.
https://github.com/canonical/steam-snap/wiki/FAQ#how-do-i-use-steam-play--proton 

### 4. List of games contains errors

https://github.com/canonical/steam-snap/wiki/Testing#suggested-games

TF2 is not small.
Floating Point is not Native (https://www.protondb.com/app/302380).

**Comment by ashuntu** [comment]
I maintain most of the wiki, so thank you for the suggestions!

1. I updated the install instructions with additional information that should be helpful: https://github.com/canonical/steam-snap/wiki#install
2. `steam.report` will notify you that you need connections when running it, they are also noted here: https://github.com/canonical/steam-snap/wiki/Troubleshooting#submitting-a-steam-report
3. `hardware-observe` shouldn't be required for all Proton games (it is, however, recommended so I added it with the install instructions, too). Is there an example of a game you can only get to work with `hardware-observe` connected?
4. The Testing section is mainly for internal use, and the game suggestions are mostly as known working games for us to test builds against.

**Comment by ashuntu** [comment]
>Is it possible to explain is detail what exactly these are for? I am also concerned about security - maybe with these connections wrapping the steam into snap doesn't make it better given all the management overhead.

Hardware and System observe shouldn't usually (in theory) be needed for games directly. However, Steam and some of its functionality may sometimes need one or the other (for example, for hardware reporting). They are also needed for `steam.report` as you've seen, and sometimes for controllers to work. In general, you should be able to use Steam and play games without either of them, some of Steam's functionality may just be a bit rough around the edges.

If you're *really* curious, everything is open source so you can view exactly what you're giving access to. See [hardware-observe](https://github.com/snapcore/snapd/blob/master/interfaces/builtin/hardware_observe.go) and [system-observe](https://github.com/snapcore/snapd/blob/master/interfaces/builtin/system_observe.go) in snapd. You can see all the other connection interfaces in snapd, too.

>Interestingly that Floating Point works, but it appeared to be native Linux binary, even while Steam and ProtonDB don't show it.

[ProtonDB](https://www.protondb.com/app/302380) notes that Floating Point is a native Linux build, but Steam doesn't report as such since it may be an unsupported build. For context, some of the games listed in Testing came from [Steam Runtime Tools](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/distro-assumptions.md#debugging-the-container-runtime-on-unusual-distributions)'s suggestions.

>Even with hardware-observe connected, no Proton title works. Downloading Unturned from the list https://github.com/canonical/steam-snap/wiki/Testing#suggested-games but I guess it won't work too.

I can get Proton games to work on my system, as well as Unturned (I am only on Intel at the moment, though). 

```
os_release: 
    name:               "Ubuntu"
    version:            "22.10 (Kinetic Kudu)"
snap_info: 
    steam_revision:     x3
    snapd_revision:     19482
lspci: 
    00:02.0:            Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] (rev 02)
    01:00.0:            NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
glxinfo: 
    gpu:                Mesa Intel(R) UHD Graphics 630 (CFL GT2)
    gpu_version:        4.6 (Core Profile) Mesa 23.2.0-devel (git-96c33fb 2023-05-30 jammy-oibaf-ppa)
lscpu: 
    model_name:         Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

**Comment by techtonik** [comment]
> [ProtonDB](https://www.protondb.com/app/302380) notes that Floating Point is a native Linux build

I don't see where. Tux is grayed out.

![image](https://github.com/canonical/steam-snap/assets/515889/d50a7aae-a660-436d-a9d5-0f32f2438e22)

Unturned also appeared to be native.
```
❯ file Unturned.x86_64 
Unturned.x86_64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.10.0, BuildID[xxHash]=8a05c17977eacb65, stripped
```

```
os_release: 
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info: 
    steam_revision:     150
    snapd_revision:     
lspci: 
    01:00.0:            NVIDIA Corporation GK106 [GeForce GTX 650 OEM] (rev a1)
glxinfo: 
    gpu:                NVE6
    gpu_version:        4.3 (Core Profile) Mesa 23.1.1 - kisak-mesa PPA
lscpu: 
    model_name:         AMD Athlon(tm) X4 740 Quad Core Processor
xdg_current_desktop:    i3
desktop_session:        i3
```

**Comment by ashuntu** [comment]
> I don't see where. Tux is grayed out.

I think this is why it's greyed out:

![image](https://github.com/canonical/steam-snap/assets/101582426/994cf38b-7531-4822-b997-94ee52beaba9)

I'm going to close this issue. If you continue having issues with Proton games, I'd suggest adding some of your experiences to the [Game Reports](https://github.com/canonical/steam-snap/discussions/categories/game-reports) discussions (and sometimes there are some insights posted there), or open a new issue for the problems you've been having if they're consistent and another similar issue doesn't already exist.

If you have any more docs suggestions, feel free to leave more comments here.

**Comment by techtonik** [comment]
[Unturned](https://www.protondb.com/app/304930) is officially Native, so there are only two recommended Proton games to test.
