### ISSUE TITLE
Installer should use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by orbitalflower** [canonical/steam-snap#244]
**Describe the bug**

On initial install, the Steam installer updates by loading data over HTTP, rather than HTTPS. HTTPS is recommended nowadays for added security.

**To Reproduce**

1. Use `snap install steam` to make a fresh Steam install.
2. Run `netstat -tpW`. Note that it's loading data from akamaitechnologies.com over HTTP, not HTTPS.

**Expected behavior**

Installer should only load data over HTTPS for security.

**Comment by ashuntu** [comment]
I'm assuming you're speaking about the Steam *installer* (after you start the Steam snap for the first time) using HTTP, in which case you should bring this issue up with Valve here: https://github.com/ValveSoftware/steam-for-linux.
