### ISSUE TITLE
Website should direct Ubuntu users to snap

### ISSUE THREAD

**Issue by orbitalflower** [canonical/steam-snap#245]
**Is your feature request related to a problem? Please describe.**

On the Steam webpage, the Install Steam button at the top right links to <https://store.steampowered.com/about/>, which automatically recommends Linux users to download the .deb installer. However, this .deb installer doesn't install cleanly in Ubuntu 23.04, perhaps because the .deb doesn't automatically install i386 prerequisites on 64-bit systems. Currently in Ubuntu 23.04, the old command `sudo apt install steam` doesn't function.

**Describe the solution you'd like**

Update the page to recommend Ubuntu users to run the terminal command `sudo snap install steam`, which installs a Steam installer which works correctly out of the box.

**Describe alternatives you've considered**

The Ubuntu snap installer app contains two entries for Steam, which may confuse users. They have poor reviews, probably due to compatibility issues in current versions. Alternate instructions for how to install a non-snap version would be valued, as many power users dislike snap install. Possible non-snap install paths are the Snap package manager (which would require an explainer on nagivating the duplicate Steam entries), `apt` plus dependencies, and installing the supplied deb via `dpkg` plus dependencies.

**Additional context**

None.

**Comment by ashuntu** [comment]
If I'm understanding right, you're suggesting a change on https://store.steampowered.com? The Steam snap is not affiliated with Valve, and unfortunately we have no control over what Valve has on their website. The .deb version of Steam *is* affiliated with Valve and "officially" supported by them, so if you have any issues with the deb specifically open them here: https://github.com/ValveSoftware/steam-for-linux (pre-reqs are also listed in this repo).
