### ISSUE TITLE
Elden Ring Fails to Launch

### ISSUE THREAD

**Issue by jardon** [canonical/steam-snap#26]
**Describe the bug**
Upon opening Elden Ring, no window opens and the process quits. 

**To Reproduce**
1. Go to Library
2. Click on Elden Ring
3. Click Play
4. Click play Elden Ring in pop-up
5. Observe the blue Cancel button return to the green Play button 

**Expected behavior**
The game should open, load EAC, and open a new game window.

**Environment**  

`snap info steam`  
```
name:      steam
summary:   Launcher for the Steam software distribution service (Early Access)
publisher: Canonical✓
store-url: https://snapcraft.io/steam
contact:   https://github.com/canonical/steam-snap
license:   unset
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
commands:
  - steam
snap-id:      NeoQngJVBf2wKC48bxnF2xqmfEFGdVnx
tracking:     latest/edge
refresh-date: yesterday at 08:44 EDT
channels:
  latest/stable:    –                              
  latest/candidate: –                              
  latest/beta:      1.0.0.74 2022-05-17 (17) 269MB -
  latest/edge:      1.0.0.74 2022-06-01 (21) 272MB -
installed:          1.0.0.74            (21) 272MB -
```

`snap version`
```
snap    2.55.5
snapd   2.55.5
series  16
ubuntu  22.04
kernel  5.15.0-33-generic
```

**Additional context**
[stdout](https://pastebin.canonical.com/p/HBXSnqMP5H/)
[denials](https://pastebin.canonical.com/p/5Ys27Kstgt/)
[system-info](https://pastebin.canonical.com/p/kbxQ89SpKc/)
[steam-1245620.log](https://github.com/canonical/steam-snap/files/8832739/steam-1245620.log)

**Comment by kenvandine** [comment]
from looking at the logs, this looks most relevant:

info:  Required Vulkan extension VK_KHR_surface not supported
55422.196:0134:0138:trace:seh:raise (22)
terminate called after throwing an instance of 'dxvk::DxvkError'

**Comment by kenvandine** [comment]
@jardon can you please test this again with steam from edge?

**Comment by ashuntu** [comment]
Closing in favor of https://github.com/canonical/steam-snap/issues/198, feel free to reopen if an Elden Ring-specific issue arises.
