### ISSUE TITLE
Include outdated libraries and current libraries for steam 

### ISSUE THREAD

**Issue by ghost** [canonical/steam-snap#262]
Certain games on Steam snap don't work because of the system and package manager including only certain components like OpenSSL 3.x whereas the game requires OpenSSL 1.x, libpcre, libidn, libxcrypt-compat and so on these need to be included in the steam snap version so that games like Age of Wonders, XCOM and so on will work out of the box.

**Comment by jssotomdz** [comment]
Do you have an exact list on which libraries and .so are needed? I'm afraid we could need two versions of the same library or libraries that are no longer available in core22 (i.e. openssl 1). I could add libpcre, libidn and libxcrypt-compat in their core22 versions but I don't own these games so I can't test it.
