### ISSUE TITLE
wiki: Typing error 'snap connect steam:audo-record'

### ISSUE THREAD

**Issue by BlackMage2** [canonical/steam-snap#269]
i found a typing error at [steam-snap/wiki](https://github.com/canonical/steam-snap/wiki): 
```
snap connect steam:audo-record
``` 

but correctly it is:
```
snap connect steam:audio-record
```

**Comment by ashuntu** [comment]
Thanks for the catch :)

**Comment by gre0j** [comment]
@ashuntu  The typo is also  in the description above…  ![Screenshot 2023-10-29 at 00-47-08 Home · canonical_steam-snap Wiki](https://github.com/canonical/steam-snap/assets/23266409/dc9525b0-e4e9-43dc-b362-b8194aa05bcb)
