### ISSUE TITLE
Buggy UI after resuming from sleep

### ISSUE THREAD

**Issue by ashuntu** [canonical/steam-snap#28]
**Describe the bug**
Sometimes after resuming from sleep, some Steam UI elements do not appear or behave incorrectly.

**To Reproduce**
1. Let the computer go to sleep with Steam open, or manually sleep
2. Resume from sleep
3. Observe odd UI behavior of Steam client

**Screenshots**
![image](https://user-images.githubusercontent.com/101582426/171935574-a5ff6af9-3409-4cfc-a816-1cf7be3472b6.png)
The Downloads page, for example.

**Environment**  
*Please provide the output of the following commands:*  

`snap info steam`  
```
...
tracking:     latest/edge
refresh-date: today at 09:04 CDT
channels:
  latest/stable:    –                              
  latest/candidate: –                              
  latest/beta:      1.0.0.74 2022-05-17 (17) 269MB -
  latest/edge:      1.0.0.74 2022-06-01 (21) 272MB -
installed:          1.0.0.74            (21) 272MB -
```

`snap version`
```
snap    2.56
snapd   2.56
series  16
ubuntu  22.04
kernel  5.15.0-33-generic
```

**Additional context**

Mousing over incorrect elements causes them to correct themselves momentarily. It also doesn't seem to happen after *every* sleep. Haven't noticed any error logs, either.

Could be related to #5

**Comment by ZoopOTheGoop** [comment]
Seems to be an nvidia-specific issue, does not occur after `prime-select`ing Intel, or on laptops with only Intel integrated. AMD is ???.
