### ISSUE TITLE
Overwatch 2 crashes after launching.

### ISSUE THREAD

**Issue by OptimoSupreme** [canonical/steam-snap#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

Game seems to run correctly on other steam packages. On Steam Snap after hitting play the game immediately crashes and never displays anything on screen.

### Expected Behavior

Game launches.

### Steps To Reproduce

Select Overwatch 2 and click play. I have this issue with all versions of Proton.

### Environment

```yaml
/usr/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
os_release: 
    name:               "Ubuntu"
    version:            "22.04.3 LTS (Jammy Jellyfish)"
snap_info: 
    steam_revision:     146
    snapd_revision:     19457
lspci: 
    03:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] (rev c7)
glxinfo: 
    gpu:                NAVI23 (navi23, LLVM 15.0.7, DRM 3.49, 6.2.0-26-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.1.4 - kisak-mesa PPA
lscpu: 
    model_name:         12th Gen Intel(R) Core(TM) i5-12400F
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

```
justin@balrog:~$ steam
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
steam.sh[18938]: Running Steam on ubuntu 22.04 64-bit
steam.sh[18938]: STEAM_RUNTIME is enabled automatically
setup.sh[19059]: Steam runtime environment up-to-date!
steam.sh[18938]: Steam client's requirements are satisfied
[2023-08-13 21:00:47] Startup - updater built Jul 28 2023 18:44:09
[2023-08-13 21:00:47] Startup - Steam Client launched with: '/home/justin/snap/steam/common/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
08/13 21:00:47 Init: Installing breakpad exception handler for appid(steam)/version(1690583737)/tid(19102)
/usr/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-08-13 21:00:47] Loading cached metrics from disk (/home/justin/snap/steam/common/.local/share/Steam/package/steam_client_metrics.bin)
[2023-08-13 21:00:47] Using the following download hosts for Public, Realm steamglobal
[2023-08-13 21:00:47] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-08-13 21:00:47] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-08-13 21:00:47] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-08-13 21:00:47] Checking for update on startup
[2023-08-13 21:00:47] Checking for available updates...
[2023-08-13 21:00:47] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-08-13 21:00:47] Manifest download: send request
[2023-08-13 21:00:48] Manifest download: waiting for download to finish
[2023-08-13 21:00:48] Manifest download: finished
[2023-08-13 21:00:48] Download skipped: /steam_client_ubuntu12 version 1690583737, installed version 1690583737, existing pending version 0
[2023-08-13 21:00:48] Nothing to do
[2023-08-13 21:00:48] Verifying installation...
[2023-08-13 21:00:48] Performing checksum verification of executable files
[2023-08-13 21:00:48] Verification complete

(process:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe8c76370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe8c74cc0
/usr/share/libdrm/amdgpu.ids: No such file or directory
GetWin32Stats: display was not open yet, good
/usr/share/libdrm/amdgpu.ids: No such file or directory
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[19148]: Runtime for steamwebhelper: defaulting to /home/justin/snap/steam/common/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
/home/justin/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 53: /proc/sys/kernel/unprivileged_userns_clone: Permission denied
/home/justin/snap/steam/common/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 60: /proc/sys/user/max_user_namespaces: Permission denied
steamwebhelper.sh[19148]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[19148]: CEF sandbox already disabled
/usr/share/libdrm/amdgpu.ids: No such file or directory
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13CAppInfoCacheReadFromDiskThread took 36 milliseconds to initialize
/usr/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13/usr/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
BRefreshApplicationsInLibrary 1: 0ms

(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Italic.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13
(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
BuildCompleteAppOverviewChange: 333 apps
RegisterForAppOverview 1: 6ms
RegisterForAppOverview 2: 7ms

(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
/bin/sh\0-c\0/home/justin/snap/steam/common/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2357570 -- /home/justin/snap/steam/common/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/justin/snap/steam/common/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/justin/snap/steam/common/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/justin/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch/Overwatch.exe'\0
chdir "/home/justin/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch"
ERROR: ld.so: object '/home/justin/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/justin/snap/steam/common/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/justin/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/justin/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/justin/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
flock /usr/share/fonts/truetype/liberation2/LiberationSans-Italic.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf LOCK_SH failed. errno = 13
(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
pressure-vessel-wrap[19562]: W: "snap/steam/146/graphics/usr/share/libdrm" is unlikely to appear in "/run/host"
pressure-vessel-wrap[19562]: W: "snap/steam/146/graphics/usr/share/libdrm" is unlikely to appear in "/run/host"
pressure-vessel-wrap[19562]: W: "snap/steam/146/graphics/usr/share/drirc.d" is unlikely to appear in "/run/host"

(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory

(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
Setting breakpad minidump AppID = 2357570
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198002079848 [API loaded no]
/usr/share/libdrm/amdgpu.ids: No such file or directory

(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
pid 19631 != 19630, skipping destruction (fork without exec?)
Game 2357570 created interface STEAMAPPLIST_INTERFACE_VERSION001 / AppList
Game 2357570 created interface STEAMAPPS_INTERFACE_VERSION008 / Apps
Game 2357570 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_004 / HTMLSurface
Game 2357570 created interface STEAMHTTP_INTERFACE_VERSION002 / HTTP
Game 2357570 created interface STEAMINVENTORY_INTERFACE_V002 / Inventory
Game 2357570 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
Game 2357570 created interface STEAMMUSIC_INTERFACE_VERSION001 / Music
Game 2357570 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
Game 2357570 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
Game 2357570 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
Game 2357570 created interface STEAMUGC_INTERFACE_VERSION010 / UGC
Game 2357570 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
Game 2357570 created interface STEAMVIDEO_INTERFACE_V002 / Video
Game 2357570 created interface SteamController006 / Controller
Game 2357570 created interface SteamFriends015 / Friends
Game 2357570 created interface SteamMatchMaking009 / Matchmaking
Game 2357570 created interface SteamMatchMakingServers002 / MatchmakingServers
Game 2357570 created interface SteamNetworking005 / Networking
Game 2357570 created interface SteamUser019 / User
Game 2357570 created interface SteamUtils009 / Utils
Game 2357570 method call count for IClientAppManager::GetCurrentLanguage : 1
Game 2357570 method call count for IClientAppManager::GetAvailableLanguages : 1
Game 2357570 method call count for IClientAppManager::GetAppInstallState : 2
Game 2357570 method call count for IClientUtils::RecordSteamInterfaceCreation : 22
Game 2357570 method call count for IClientUtils::GetSteamUILanguage : 1
Game 2357570 method call count for IClientUtils::GetAppID : 24
Game 2357570 method call count for IClientUser::GetSteamID : 1
Uploaded AppInterfaceStats to Steam

(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed

(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed

(steam:19102): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
```

**Comment by paytime** [comment]
It is still not working on the Snap version, while it run fine on all other versions. Please take a look at this issue as it might affect other Blizzard games too as soon as they launch on Steam (such as Diablo 4).

Logs:
`/bin/sh\0-c\0/home/user/snap/steam/common/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2357570 -- /home/user/snap/steam/common/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/user/snap/steam/common/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch/Overwatch.exe'\0
chdir "/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch"
ERROR: ld.so: object '/home/user/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/snap/steam/common/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/user/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:197681): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed

(steam:197681): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libEGL_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libEGL_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libGLX_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libGLX_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libEGL_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libEGL_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libGLX_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libGLX_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libEGL_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
i386-linux-gnu-capsule-capture-libs: warning: Dependencies of libGLX_nvidia.so.0 not found, ignoring: Missing dependencies: Could not find "libnvidia-glsi.so.535.113.01" in LD_LIBRARY_PATH "/snap/steam/165/graphics/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib:/snap/steam/165/usr/lib/i386-linux-gnu:/snap/steam/165/lib/i386-linux-gnu:/snap/steam/165/usr/lib/i386-linux-gnu/pulseaudio:/snap/steam/165/usr/lib/x86_64-linux-gnu/alsa-lib:/snap/steam/165/usr/lib/x86_64-linux-gnu/pulseaudio:/snap/steam/165/graphics/usr/lib/i386-linux-gnu:/snap/steam/165/graphics/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib:/home/user/snap/steam/common/.local/share/Steam/steamapps/common/Overwatch", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
pressure-vessel-wrap[199118]: W: "snap/steam/165/graphics/usr/share/libdrm" is unlikely to appear in "/run/host"
pressure-vessel-wrap[199118]: W: "snap/steam/165/graphics/usr/share/libdrm" is unlikely to appear in "/run/host"
pressure-vessel-wrap[199118]: W: "var/lib/snapd/hostfs/usr/share/drirc.d" is unlikely to appear in "/run/host"
pressure-vessel-wrap[199118]: W: "snap/steam/165/graphics/usr/share/drirc.d" is unlikely to appear in "/run/host"
pressure-vessel-wrap[199118]: W: "var/lib/snapd/hostfs/usr/share/nvidia" is unlikely to appear in "/run/host"
pressure-vessel-wrap[199118]: W: "var/lib/snapd/hostfs/usr/share/nvidia" is unlikely to appear in "/run/host"
Uploaded AppInterfaceStats to Steam

(steam:197681): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed

(steam:197681): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
`

**Comment by ashuntu** [comment]
If not already, this may work now with 2.64 snapd. You can try by refreshing snapd with snap refresh snapd --edge (and restarting). Make sure to go back to stable after testing with snap refresh snapd --stable.
