### ISSUE TITLE
Northgard fails to launch due to missing libraries

### ISSUE THREAD

**Issue by Henne1191** [canonical/steam-snap#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [ ] This is a Steam Snap-specific issue

### Current Behavior

the game does not start, running from a terminal shows the following errors:
```
/bin/sh\0-c\0/home/hendrik/snap/steam/common/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=466560 -- /home/hendrik/snap/steam/common/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/hendrik/snap/steam/common/.local/share/Steam/steamapps/common/Northgard/linux/run.sh'\0
chdir "/home/hendrik/snap/steam/common/.local/share/Steam/steamapps/common/Northgard"
flock /usr/share/fonts/truetype/msttcorefonts/Arial_Italic.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/msttcorefonts/Arial.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/msttcorefonts/Arial.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/msttcorefonts/Arial.ttf LOCK_SH failed. errno = 13flock /usr/share/fonts/truetype/msttcorefonts/Arial.ttf LOCK_SH failed. errno = 13
(steam:32916): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed

(steam:32916): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
ERROR: ld.so: object '/home/hendrik/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hendrik/snap/steam/common/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/hendrik/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hendrik/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
** ERROR ** Missing library libXss.so.1
** ERROR ** Missing library libpulsecommon-15.99.so
** ERROR ** Missing library libXss.so.1
** ERROR ** Missing library libpulsecommon-15.99.so
** ERROR ** Missing library libXss.so.1
** ERROR ** Missing library libpulsecommon-15.99.so
** ERROR ** Missing library libXss.so.1
** ERROR ** Missing library libpulsecommon-15.99.so
** ERROR ** Missing library libXss.so.1
** ERROR ** Missing library libpulsecommon-15.99.so
sh: 1: notify-send: not found
src/module.c(373) : FATAL ERROR : Failed to load library sdl.hdll
```

### Expected Behavior

the game should just start

### Environment

```yaml
os_release: 
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info: 
    steam_revision:     154
    snapd_revision:     19993
lspci: 
    00:02.0:            Intel Corporation Iris Graphics 540 (rev 0a)
glxinfo: 
    gpu:                Mesa Intel(R) Iris(R) Graphics 540 (SKL GT3)
    gpu_version:        4.6 (Core Profile) Mesa 23.1.6 - kisak-mesa PPA
lscpu: 
    model_name:         Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### Anything else?

Maybe a regression? https://github.com/canonical/steam-snap/issues/19

**Comment by ashuntu** [comment]
This looks similar to https://github.com/canonical/steam-snap/issues/262 as well as #19, though I'm not sure what resolved the issue in #262.

In #19 we discovered Northgard overwrites `LD_LIBRARY_PATH`, but it should have been resolved. 

If you run `snap run --shell steam`, can you verify that those libraries exist in `$SNAP` (e.g. `find $SNAP -name libpulsecommon-15.99.so`)

**Comment by Henne1191** [comment]
This is the output I am getting:
`hendrik@hendrik-XPS-13-9350:~$ snap run --shell steam
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

hendrik@hendrik-XPS-13-9350:/home/hendrik$ find $SNAP -name libpulsecommon-15.99.so
/snap/steam/154/usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-15.99.so
hendrik@hendrik-XPS-13-9350:/home/hendrik$ find $SNAP -name libXss.so.1
hendrik@hendrik-XPS-13-9350:/home/hendrik$`

So it seems one does exist and one does not?

**Comment by ashuntu** [comment]
If you could, try this build of the snap: https://github.com/canonical/steam-snap/actions/runs/10376717242/artifacts/1808536272. Download the file, unzip it, and then run `snap install *.snap --dangerous`. Also make sure you are on edge snapd with `snap refresh snapd --edge`. Let me know if that build works for you and any errors you encounter.

**Make sure to go back to stable versions after testing:**
```
snap refresh steam --stable --amend
snap refresh snapd --stable
```

**Comment by ashuntu** [comment]
Should be fixed by https://github.com/canonical/steam-snap/commit/ea78c8076b00d0a3a0893f9a40899a897ac5ac83, expect the fix to be in the edge channel of the Steam snap in a few hours. If this doesn't fully resolve the issue, feel free to reopen.
