### ISSUE TITLE
No audio playback

### ISSUE THREAD

**Issue by DefaultX-od** [canonical/steam-snap#3]
As the title says there is no sound nor from steam nor from native game that I tried. Tested it on 2 machines with Ubuntu 20.04.4, and in a VM with Ubuntu 22.04

**Comment by kenvandine** [comment]
I can't reproduce the issue on either 20.04 or 22.04.  Can you please capture standout out from running steam in a terminal window and add it to this bug report?

**Comment by DefaultX-od** [comment]
Is, **snap run steam stdout.txt 2> stderr.txt**, correct way to capture it?
If yes, then I attach that file.
[stderr.txt](https://github.com/canonical/steam-snap/files/8608396/stderr.txt)

**Comment by DefaultX-od** [comment]
And here are 2 screencasts, where nothing happens in Volume Levels in settings app.
In first one, I play a trailer from the store page, and normally "Chromium" would appear in Volume Levels, but here nothing happens:

https://user-images.githubusercontent.com/61311905/166410273-9bd42f44-75ff-42e0-9eef-ddaf65e2a5fb.mp4

And in the second one, I open a game, and again no sound:

https://user-images.githubusercontent.com/61311905/166410315-b7f61236-4749-4247-b022-9ea701ecb975.mp4

**Comment by DenX** [comment]
I'm running into the same issue under a fresh installed Ubuntu 22.04.
I can see the below error in the steamwebhelper logs every time I hit the play button. Could this be related to both trailer and in-game audio missing? 

`ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
[0503/163808.081236:ERROR:alsa_util.cc(204)] PcmOpen: default,No such file or directory
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
[0503/163808.081359:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,No such file or directory`

**Comment by DefaultX-od** [comment]
Regarding games, it seems that some are able (BlackSmith HIT) to produce audio and some are not (Muck, Suicide guy).

**Comment by DenX** [comment]
I can confirm sounds in big picture work (although not all of them like the intro video). None of the games (Crusader Kings 3, Stardew Valley) I tried have sound though.

I have been digging deeper regarding the videos in the store. For some reason it falls back to Alsa because it thinks the PulseAudio device is unavailable. 
But Alsa also doesn't work either. I can see Steam trying to talk to DBus.
```
audit: type=1107 audit(1651665916.244:992): pid=1085 uid=102 auid=4294967295 ses=4294967295 subj=? msg='apparmor="DENIED" operation="dbus_signal"  bus="system" path="/org/freedesktop/login1" interface="org.freedesktop.DBus.Properties" member="PropertiesChanged" name=":1.17" mask="receive" pid=39725 label="snap.steam.steam" peer_pid=1115 peer_label="unconfined" exe="/usr/bin/dbus-daemon" sauid=102 hostname=? addr=? terminal=?'
audit: type=1420 audit(1651665916.244:993): subj_apparmor=unconfined
audit: type=1107 audit(1651665922.384:994): pid=1085 uid=102 auid=4294967295 ses=4294967295 subj=? msg='apparmor="DENIED" operation="dbus_signal"  bus="system" path="/org/freedesktop/login1" interface="org.freedesktop.DBus.Properties" member="PropertiesChanged" name=":1.17" mask="receive" pid=39725 label="snap.steam.steam" peer_pid=1115 peer_label="unconfined" exe="/usr/bin/dbus-daemon" sauid=102 hostname=? addr=? terminal=?'
audit: type=1420 audit(1651665922.384:995): subj_apparmor=unconfined
```
After building the steam snap with DBus support I get further but still fail due to AppArmor denying access.
```
audit: type=1400 audit(1651662343.436:300): apparmor="DENIED" operation="open" profile="snap.steam.steam" name="/dev/snd/controlC0" pid=36486 comm="steamwebhelper" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
audit: type=1400 audit(1651662343.436:301): apparmor="DENIED" operation="open" profile="snap.steam.steam" name="/dev/snd/controlC1" pid=36486 comm="steamwebhelper" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
audit: type=1400 audit(1651662343.436:302): apparmor="DENIED" operation="open" profile="snap.steam.steam" name="/dev/snd/controlC2" pid=36486 comm="steamwebhelper" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
audit: type=1400 audit(1651662343.440:303): apparmor="DENIED" operation="open" profile="snap.steam.steam" name="/etc/alsa/conf.d/" pid=36486 comm="steamwebhelper" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```
@kenvandine is there an easy way for me generate AppArmor profiles for snaps while I debug (sorry I'm new to Ubuntu and AppArmor)?

**Comment by kenvandine** [comment]
Thanks for helping to debug.  Could you please comment with your
connections?

snap connections steam

I can't test right now as I'm traveling, but this was working for me.

**Comment by DenX** [comment]
See my connections below. Please ignore the dbus interface, it's my build for debugging. I've enabled some of the control and observe interfaces without much success.

```
Interface               Plug                          Slot                            Notes
audio-playback          steam:audio-playback          :audio-playback                 -
audio-record            steam:audio-record            -                               -
bluez                   steam:bluez                   -                               -
content[gtk-3-themes]   steam:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    steam:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   steam:sound-themes            gtk-common-themes:sound-themes  -
dbus                    -                             steam:dbus-daemon               -
desktop                 steam:desktop                 :desktop                        -
desktop-legacy          steam:desktop-legacy          :desktop-legacy                 -
fuse-support            steam:fuse-support            :fuse-support                   manual
gsettings               steam:gsettings               :gsettings                      -
hardware-observe        steam:hardware-observe        :hardware-observe               manual
home                    steam:home                    :home                           -
joystick                steam:joystick                -                               -
mount-observe           steam:mount-observe           -                               -
network                 steam:network                 :network                        -
network-control         steam:network-control         :network-control                manual
opengl                  steam:opengl                  :opengl                         -
personal-files          steam:dot-local-share-steam   -                               -
process-control         steam:process-control         :process-control                manual
removable-media         steam:removable-media         -                               -
screen-inhibit-control  steam:screen-inhibit-control  :screen-inhibit-control         -
shared-memory           steam:shared-memory           :shared-memory                  -
steam-support           steam:steam-support           :steam-support                  -
system-observe          steam:system-observe          :system-observe                 manual
wayland                 steam:wayland                 :wayland                        -
x11                     steam:x11                     :x11                            -

```

**Comment by kenvandine** [comment]
All the necessary interfaces are connected, thanks for that info.  I'm
traveling this week, but should be able to help debug this later in the
week.  Thanks for the testing, it's much appreciated.

**Comment by kenvandine** [comment]
Reopened until we have confirmation it fixes both audio in gameplay and webview playback.

**Comment by DenX** [comment]
Unfortunately this doesn't fix the audio playback. I've built the snap based on the latest main branch.
PulseAudio still cannot be initialized.
```
[0507/101655.191618:WARNING:audio_manager_linux.cc(58)] Falling back to ALSA for audio output. PulseAudio is not available or could not be initialized.
```
ALSA log output has changed. It complains about a missing lib now.
```
[0507/101655.192118:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{},\"stack\":[{\"file\":\"../../media/filters/decrypting_video_decoder.cc\",\"line\":53}],\"status_code\":264,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"DecryptingVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
ALSA lib dlmisc.c:283:(snd_dlobj_cache_get0) Cannot open shared library /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so ((null): libsndfile.so.1: cannot open shared object file: No such file or directory)
[0507/101655.192997:ERROR:alsa_util.cc(204)] PcmOpen: default,No such device or address
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM plug:default
[0507/101655.193018:ERROR:alsa_util.cc(204)] PcmOpen: plug:default,No such file or directory
```

**Comment by DenX** [comment]
Created PR #15 which fixes this issue
