### ISSUE TITLE
Removing Steam Snap can lead to a full system partition because of automatic snapshot

### ISSUE THREAD

**Issue by gre0j** [canonical/steam-snap#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

When I installed Ubuntu 23.04, I created a system partition (60GB) and a home partition (440GB). Now Steam easily reaches several hundred GB by installing large games. 

If you now want to remove Steam Snap, a snapshot is automatically created on the system partition, which can then lead to the fact that the system partition comes to its capacity limit. Furthermore, the uninstallation takes a very long time. 

After I disabled the automatic creation of the snapshot, the uninstallation was very fast. 

https://snapcraft.io/docs/system-options#heading--snapshots-automatic-retention

### Expected Behavior

No system freeze and a faster deinstallation? Maybe this is just a problem for steam, because of the folder size. Deactivate snapshots for steam?

### Environment

```yaml
Sorry, removed Steam before
```

### gaming-graphics-core22 version

kisak-fresh (default)

**Comment by ashuntu** [comment]
Your only other alternative is to purge Steam when you uninstall to prevent a snapshot with `snap remove --purge steam`.

There isn't anything we can do for the snap to do this automatically, but I've added a [section in the wiki](https://github.com/canonical/steam-snap/wiki#uninstall) with this information.

**Comment by gre0j** [comment]
Thank you for the hint in the wiki. I noticed `snap set system snapshots.automatic.retention=yes` doesn't work.
I read: _The value needs to be greater than 24 hours._

Is this default of 31 days correct: `snap set system snapshots.automatic.retention=744h` ?

**Comment by ashuntu** [comment]
Ah yes, my bad, that is correct
