### ISSUE TITLE
Factorio permission error on launch

### ISSUE THREAD

**Issue by kristbaum** [canonical/steam-snap#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

When launching factorio, it reports:
filesystem error: cannot create directory: Permission denied [/home/username/.factorio]
path1: /home/username/.factorio

### Expected Behavior

Should try to create a folder in the home, maybe setting the factorio setting: use-system-read-write-data-directories to false could help. Another user had a similar problem #136 but closed the issue.

### Steps To Reproduce

Try to start Factorio from the snap steam version

### Environment

```yaml
stable
```

**Comment by rbobrowicz** [comment]
There is a workaround in the Wiki: https://github.com/canonical/steam-snap/wiki/Known-Workarounds#factorio

**Comment by ashuntu** [comment]
> There is a workaround in the Wiki: https://github.com/canonical/steam-snap/wiki/Known-Workarounds#factorio

This is the current best solution. If the wiki solution doesn't work either, please reopen this issue.
