### ISSUE TITLE
no game starts in my snap installation

### ISSUE THREAD

**Issue by BlackMage2** [canonical/steam-snap#315]
No game starts in my snap steam installation

for example when i try to start factorio:
Couldn't create lock file /home/user/.factorio/.lock

other games starts not at all

Why steam try to write in .factorio directory for factorio in users home and not in the snap steam directory?

And how i can change it?

**Comment by BlackMage2** [comment]
the https://github.com/canonical/steam-snap/wiki/Known-Workarounds#factorio workaround works not

**Comment by ashuntu** [comment]
The workaround at https://github.com/canonical/steam-snap/wiki/Known-Workarounds#factorio works for me, I just tried it.

Can you paste the output of these commands:
```
cat ~/snap/steam/common/.steam/steam/steamapps/common/Factorio/config-path.cfg
cat ~/snap/steam/common/.steam/steam/steamapps/common/Factorio/config/config.ini
```

**Comment by BlackMage2** [comment]
sure
```
cat ~/snap/steam/common/.steam/steam/steamapps/common/Factorio/config/config.ini
config-path=__PATH__system-write-data__/config

#This value specifies the way the application generates default values for path.read-data and path.write-data
#When set to true, it will use system directories (Users/Name/AppData/Roaming/Factorio on windows), this is set to true
#for the installer versions of Factorio, as people will usually install it in program files, and the application can't write
#to program files by default (without UAC turned off), similar with osx/linux packages.
#When set to false (default value for zip package), it will use application root directory, this is usable to create self-sustainable
#Factorio directory that can be copied anywhere needed (on usb etc), also for people, who don't like to manipulate saves
#in the windows users directory structure (as me, kovarex).
#Note, that once the values in config are generated, this value has no effects (unless you delete config, or the path.read-data/path.write-data values)
use-system-read-write-data-directories=true
[path]
read-data=__PATH__executable__/../../data
write-data=__PATH__executable__/../../writedata

``` 

the files i have created

**Comment by ashuntu** [comment]
Looks like you may have missed steps 2 and 3, `use-system-read-write-data-directories=true` should be `use-system-read-write-data-directories=false` and `config-path=__PATH__system-write-data__/config` should be `config-path=__PATH__executable__/../../config` (note the `../../`) in `~/snap/steam/common/.steam/steam/steamapps/common/Factorio/config-path.cfg`.

**Comment by BlackMage2** [comment]
Yes, thank you very much. :D

It works now.

my mistake

**Comment by BlackMage2** [comment]
sry, it doesn't work. all user data is missing

**Comment by ashuntu** [comment]
What data is missing? Are you talking about previous saves from another version of Steam?

**Comment by BlackMage2** [comment]
yes

hmpf, in the previous Steam installation I managed to use $HOME/.factorio in the Steam version, but that's not important

i have copied data in .factorio to writedata directory and all works
