### ISSUE TITLE
Steam Snap doesn't make use of external GPU, Debian Package does.

### ISSUE THREAD

**Issue by PhonicUK** [canonical/steam-snap#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

When running with an attached external GPU (In this case, a RTX 3070 over USB 4) - the Snap version of Steam cannot make use of the external GPU, and both steam itself and launched applications will only use the iGPU. `nvidia-smi` shows that the GPU is not being used. 

### Expected Behavior

Like the non-snap package, Steam itself and launched games should make use of the eGPU. 

### Steps To Reproduce

1. Install and configure an external GPU over USB4/Thunderbolt
2. Observe that the system is able to run applications on the GPU, such as by using `glxinfo` / `vulkaninfo`
3. Install the Steam snap
4. Install any game via Steam
5. Observe poor performance in the game
6. Verify with `nvidia-smi` or other similar tool to verify external GPU isn't  being used.

### Environment

```yaml
Snap output unavailable at time of writing.

Ubuntu 23.10
Framework 13 AMD Edition - AMD Ryzen 7 7840U w/ Radeon 780M Graphics
nVidia RTX 3070 via Razer Core eGPU enclosure over USB 4
Wayland Desktop environment
```

**Comment by ErickLandowski** [comment]
I could be wrong here, but maybe by any chance you need to enable the "removable-media" connection for Steam?

**Comment by ashuntu** [comment]
Probably related to https://github.com/canonical/steam-snap/issues/195 and https://github.com/canonical/steam-snap/issues/14.

Does passing the arguments from #195 to the game's launch command work? What about right-clicking Steam and running with discrete GPU (if you're on GNOME)?

> I could be wrong here, but maybe by any chance you need to enable the "removable-media" connection for Steam?

This *should* be connected by default. OP could try connecting hardware-observe and system-observe, but they most likely will not help this issue.
