### ISSUE TITLE
Allow reading /etc/debian_chroot

### ISSUE THREAD

**Issue by smcv** [canonical/steam-snap#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution/feature you'd like.

As a convenience for developers, pressure-vessel sets up `/etc/debian_chroot` to identify its container. This means that if you happen to be using Debian's default `/etc/bash.bashrc`, you get the name and version of the container in your prompt, making it much easier to tell at a glance what environment you're in.

Unfortunately this Snap app has an AppArmor profile that does not allow reading `/etc/debian_chroot`, so this doesn't actually work.

To see this, try running a Proton or Steam Linux Runtime game with Launch Options set to `PRESSURE_VESSEL_SHELL=instead %command%`. Instead of the game, you'll get an interactive shell in an `xterm`. When running Steam from .deb packaging, your prompt in that `xterm` will contain the name and version of the container. When running the Snap app, it doesn't, and instead you get `cat: /etc/debian_chroot: Permission denied`.

**Comment by smcv** [comment]
As with #361, this change is not actually going to take effect until a snapd release with 13565 has been rolled out to all users. After a suitable version is widely available, perhaps `snapcraft.yaml → assumes → snapdX.Y.Z` should be updated, to guarantee that all users of this app actually have it?

**Comment by ashuntu** [comment]
> As with #361, this change is not actually going to take effect until a snapd release with 13565 has been rolled out to all users. After a suitable version is widely available, perhaps `snapcraft.yaml → assumes → snapdX.Y.Z` should be updated, to guarantee that all users of this app actually have it?

Yes, this is something we will do. A draft PR is here: https://github.com/canonical/steam-snap/pull/367
