### ISSUE TITLE
Should allow reading /sys/module/nvidia/version

### ISSUE THREAD

**Issue by smcv** [canonical/steam-snap#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is the feature related to a problem or existing issue?

Probably helps #350

### Describe the solution/feature you'd like.

To make it possible to solve non-functional Vulkan in Steam Linux Runtime / Proton games, I want to apply https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/652 to pressure-vessel. However, that isn't going to work unless we can discover the active Nvidia driver version.

Flatpak also needs to know the Nvidia driver version (because Nvidia requires user-space and kernel drivers to be in lockstep), and it achieves that by reading `/sys/module/nvidia/version`. This seems like a generally useful thing to make possible, and doesn't seem like a security hazard.

### Describe any alternatives you've considered.

In the long term, https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/123 should provide a better way to discover which files are required for the Nvidia driver to have its proper functionality, but I can't make progress on that until a concrete specification is proposed.

**Comment by ashuntu** [comment]
This should be fixed by https://github.com/snapcore/snapd/pull/13565.

**Comment by smcv** [comment]
Thanks!

For clarity: this change is not actually going to take effect until a snapd release with 13565 has been rolled out to all users. After a suitable version is widely available, should `snapcraft.yaml → assumes → snapdX.Y.Z` should be updated, to guarantee that all users of this app actually have it?
