### ISSUE TITLE
Should allow pressure-vessel to mask /snap/steam/171/usr/share/vulkan/implicit_layer.d with a tmpfs

### ISSUE THREAD

**Issue by smcv** [canonical/steam-snap#370]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

While testing a new Steam Linux Runtime release on an Ubuntu 22.04 system with the Nvidia proprietary drivers, its startup failed with: `bwrap: Can't mount tmpfs on /newroot/snap/steam/171/usr/share/vulkan/implicit_layer.d: Permission denied`.

pressure-vessel requires the ability to "mask" search path entries for Vulkan layers so that its own carefully-managed search path will take precedence, because there is currently no way to disable Vulkan-Loader's built-in search paths for implicit layers (only prepend to them), and we have seen crashes in the past that were triggered by drivers and layers being enumerated twice.

At the moment, the AppArmor profile allows us to mask `~/.local/share/vulkan/implicit_layer.d` but not `/snap/steam/171/usr/share/vulkan/implicit_layer.d`.

### Expected Behavior

Should allow pressure-vessel to do what it needs to do.

### Steps To Reproduce

Sorry, I do not currently have the time available to verify whether this is reproducible with released SLR versions.

### Environment

```yaml
not provided
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

I was able to work around this by hacking `mount fstype=tmpfs options=(rw, nosuid, nodev) tmpfs -> /**` into the AppArmor profile, and reloading it. This means that https://github.com/snapcore/snapd/pull/13489 should resolve this automatically, when released.

**Comment by smcv** [comment]
As with #369, this is a critical issue, because it now breaks startup of the Steam user interface.

**Comment by ashuntu** [comment]
https://github.com/snapcore/snapd/pull/13489 was merged, so this can be closed since it should cover the requirement.

**Comment by smcv** [comment]
> this can be closed since it should cover the requirement

Has the necessary version of snapd been released, and does this Snap app require it?

**Comment by ashuntu** [comment]
It's available in the `edge` channel of snapd at present. When it's available in stable (the PR is marked for 2.62 currently), we will update this snap's `assumes` to the current stable `snapd` version.

**Comment by jbicha** [comment]
Do you have a release date for the snapd version that will fix this issue? smcv is concerned that a new release of Steam could happen before then.

**Comment by ashuntu** [comment]
> Do you have a release date for the snapd version that will fix this issue? smcv is concerned that a new release of Steam could happen before then.

I've heard they're targeting the start of April, but I don't know for certain.

**Comment by smcv** [comment]
pressure-vessel 0.20240306.0, as included in Steam client update 1709846872, has a temporary workaround for this. The workaround will be removed when a suitable snapd has shipped (please let us know when).

To reproduce the issue, replace the `pressure-vessel/` directory with the result of unpacking https://repo.steampowered.com/pressure-vessel/snapshots/0.20240301.0/pressure-vessel-bin.tar.gz which does not have this workaround. (In future pressure-vessel releases I'll probably add an environment variable that turns off workarounds, to facilitate testing of this sort of thing.)

**Comment by smcv** [comment]
The latest pressure-vessel build https://repo.steampowered.com/pressure-vessel/snapshots/0.20240321.0/ has a generic mechanism to activate and deactivate workarounds. This is likely to be in the next sniper beta (hopefully later today, but I don't control the exact schedule) and also in a future Steam beta. My plan is that next time we need a workaround for Snap not allowing something that we need, it'll go through the same mechanism, so that you can easily turn the workaround off for testing.  I hope this will help you out.

You can try this version early by unpacking https://repo.steampowered.com/pressure-vessel/snapshots/0.20240321.0/pressure-vessel-bin.tar.gz into (for example) `~/tmp/pressure-vessel`, and then running Steam with `PRESSURE_VESSEL_PREFIX=$HOME/tmp/pressure-vessel` in the environment.

Because we can't yet count on having an updated version of Snap, the workaround for this issue is active by default if we detect Snap. You can deactivate it for testing by adding environment variable `PRESSURE_VESSEL_WORKAROUNDS="-steam-snap#370"`, which will cause pressure-vessel to fail with current versions of snapd, but will hopefully work with the snapd where https://github.com/snapcore/snapd/pull/13489 has been integrated.

It's a space- or comma-separated list, and each item starts with a `+` or `-` to activate or deactivate a workaround, so to change the state of more than one workaround you can say something like `PRESSURE_VESSEL_WORKAROUNDS="-steam-snap#359 +steam-snap#356"`. We also use this mechanism for workarounds for non-Snap systems where we have to use a setuid copy of bubblewrap that might be outdated.

After this app gains a dependency on a new enough snapd, we'll set the workaround to be inactive by default, and probably remove the code for it completely, either immediately or a few days/weeks later.

**Comment by smcv** [comment]
If I'm keeping track correctly, this was fixed in snapd 2.62, which is mandatory since #367. As a result, the pressure-vessel version included in yesterday's SLR soldier and sniper beta releases disables our workaround for this issue by default. If there are no regression reports in the next few days/weeks, we will remove the workaround completely.

The status of this issue is similar to https://github.com/canonical/steam-snap/issues/356#issuecomment-1912411145.

If it becomes necessary to re-enable the workaround, you can do this:

1. Report an issue to https://github.com/ValveSoftware/steam-runtime/issues so we can enable it by default again, and so that we know that we can't delete the implementation of the workaround yet
2. Run with `PRESSURE_VESSEL_WORKAROUNDS="+steam-snap#370"` in the environment (if you need to use more than one workaround, it's a space-separated list)
