### ISSUE TITLE
Steam suggests installing to "/boot"

### ISSUE THREAD

**Issue by ZVNexus** [canonical/steam-snap#373]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

When I try to install a game it suggests installing to the default drive "/boot".

### Expected Behavior

It doesn't try installing to "/boot".

### Steps To Reproduce

sudo snap install steam

Try to install a game

### Environment

```yaml
nexus@prism:~$ snap run steam.report
mkdir: cannot create directory ‘/run/user/0’: Permission denied
find: ‘/root/snap/steam/common/.local/share/applications’: No such file or directory
find: Failed to restore initial working directory: /home/nexus: Permission denied
find: ‘/root/snap/steam/common/.local/share/icons/hicolor’: No such file or directory
find: Failed to restore initial working directory: /home/nexus: Permission denied
ln: failed to create symbolic link '/root/.local/share/applications/': No such file or directory
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Traceback (most recent call last):
  File "/snap/steam/171/bin/steamreport", line 472, in <module>
    main()
  File "/snap/steam/171/bin/steamreport", line 468, in main
    create_window(args)
  File "/snap/steam/171/bin/steamreport", line 402, in create_window
    window = SteamReportWindow(args)
  File "/snap/steam/171/bin/steamreport", line 29, in __init__
    super().__init__()
  File "/snap/steam/171/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
steam-runtime-launcher-service: no process found
nexus@prism:~$
```
Ubuntu 24.04
ASUS Crosshair X670E Hero
AMD R9 7950X
AMD RX 7900 XTX
96GB DDR5

**Comment by ashuntu** [comment]
If you go to Settings > Storage what does it list the default storage device as? You may see an odd path as the drive name (it's usually something like `/usr/lib/modules`), but the full path should be listed as something like `/home/<your_computer_username>/snap/steam/common/.local/share/Steam`.

![image](https://github.com/canonical/steam-snap/assets/101582426/486612bc-430f-4392-b526-5ba3f7b1db46)

*This isn't in regard to your specific issue, but you may want to try running `sudo /usr/lib/snapd/snap-discard-ns steam` to fix that `steam.report` error. If that doesn't work, you may need to restart your computer. If you do get a normal `steam.report` response, please update the issue with its information.*

**Comment by ZVNexus** [comment]
> You may see an odd path as the drive name (it's usually something like /usr/lib/modules)

This is what it shows up as for the first install, but after changing snap connections detailed in the wiki it changes to /boot.
![image](https://github.com/canonical/steam-snap/assets/19439046/dc4feb85-1a5e-445d-9bbb-64b9e83b8acc)

**Comment by ashuntu** [comment]
> This is what it shows up as for the first install, but after changing snap connections detailed in the wiki it changes to /boot.

It really shouldn't matter what the drive is called, as long as the full path points to `~/snap/steam/common/.local/share/Steam` then it is fine (which yours indeed does). You can also verify it's correct by stalling a game and then running `ls ~/snap/steam/common/.local/share/Steam/steamapps/common` from a terminal, that's where your games should be installed to by default.

As far as I know, the drive name isn't something we have control over, so I'm going to close this issue for now.

> I actually get a different output after running that, but it's still errors. Updated comment, put some rough details on my current environment.

Interesting. Thanks for updating the description.

**Comment by mirao** [comment]
Got this after installation of Steam to a fresh OS:

![image](https://github.com/user-attachments/assets/9bc4bccd-a21a-4208-b7a5-812b15157648)

![image](https://github.com/user-attachments/assets/eaed9b25-8243-47be-8b89-f5b28953d5a4)

It's confusing that storage is displayed as `/usr/lib/modules`, however a location for Steam games seems to be correct and a game can be installed as expected.

Tested on Ubuntu 24.04 with Steam 1721173382 (snap steam ver. 1.0.0.79)

**Comment by stefanlasiewski** [comment]
> the drive name isn't something we have control over,

If that's the case, this bug needs to be mentioned in a prominent place, such as a FAQ at [snapcraft.io/steam](https://snapcraft.io/steam) as suggested by o-alquimista. Leaving it along is a bad look for Snap.

**Comment by ashuntu** [comment]
This quirk is noted in our GitHub wiki here: https://github.com/canonical/steam-snap/wiki/FAQ#how-do-i-add-external-libraries-or-games.
