### ISSUE TITLE
Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by 1pinus** [canonical/steam-snap#381]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

snap run steam steam://rungameid/281990
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
INFO: filtering /usr/share/ubuntu-xorg out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /usr/share/gnome out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /var/lib/snapd/desktop out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /etc/xdg/xdg-ubuntu-xorg out of XDG_CONFIG_DIRS because it is unreachable
INFO: filtering /etc/xdg out of XDG_CONFIG_DIRS because it is unreachable
steam.sh[1748866]: Running Steam on ubuntu 24.04 64-bit
steam.sh[1748866]: STEAM_RUNTIME is enabled automatically
Gtk-Message: 21:34:41.843: Failed to load module "xapp-gtk3-module"
setup.sh[1748961]: Steam runtime environment up-to-date!
steam.sh[1748866]: Steam client's requirements are satisfied
Steam is already running, exiting (command line was forwarded).

### Expected Behavior

That the game starts, but it doesn't start.

### Steps To Reproduce

On the command line.
snap run steam steam://rungameid/281990

### Environment

```yaml
# Systemdetailsbericht
---

## Berichtdetails
- **Erstellungsdatum:**                            2024-05-08 21:44:06

## Hardware-Informationen:
- **Hardware-Modell:**                             ASUSTeK COMPUTER INC. PRIME X470-PRO
- **Speicher:**                                    64,0 GiB
- **Prozessor:**                                   AMD Ryzen™ 9 5900X × 24
- **Grafik:**                                      AMD Radeon™ RX 7600
- **Festplattenkapazität:**                        10,8 TB

## Software-Informationen:
- **Firmware-Version:**                            6063
- **Name des Betriebssystems:**                    Ubuntu 24.04 LTS
- **Betriebssystem-Build:**                        (null)
- **Betriebssystem-Typ:**                          64-bit
- **GNOME-Version:**                               46
- **Fenstermanager:**                              X11
- **Kernel-Version:**                              Linux 6.8.8-060808-generic
```

**Comment by ashuntu** [comment]
Are you able to run the game directly from the Steam client?

**Comment by 1pinus** [comment]
No. Removed the snap and installed the Steam-deb. Now everything is fine.
