### ISSUE TITLE
Import all installed games from multiple sources

### ISSUE THREAD

**Issue by luisalvarado** [canonical/steam-snap#394]
This is not a bug, just a question about installing the steam snap version and making sure that it will see the games I have already installed. My particular case is that I have games installed in various storage devices as seen here:

![2024-07-19_08-46](https://github.com/user-attachments/assets/e5c19823-039f-4f75-879d-a6eede7dff61)

So based on this, if I install steam snap, it will read the current installed games on those drivers and automatically be able to use them?

This is for a particular group of videos I will be making soon. Thank you.

**Comment by ashuntu** [comment]
You should be able to add those paths to the Steam UI and have their games show up like they would with the Steam deb. You can have the snap and the deb installed at the same time, so feel free to test for yourself.

**Comment by luisalvarado** [comment]
Hi team Steam snap, here is a video to explain this further and help with testing it in further versions:

https://www.youtube.com/watch?v=ZFtVshoSIi8

**Comment by luisalvarado** [comment]
I was able to add the external ones, but there is no way of adding the steamapps folder from the home folder. It basically fails to get added, so any games in it dont show because the actual storage does not get added if that explains it. BTW, just tested several games. Performance is on par with DEB, including demanding games like spiderman remastered.

**Comment by ashuntu** [comment]
If you *can* add games from the Steam deb, you'll likely need `dot-local-share-steam` connected with `snap connect steam:dot-local-share-steam` from a terminal. However, adding a library like this isn't recommended anyway, you'd be better off using external drives or mounts for shared games instead.

**Comment by luisalvarado** [comment]
It is still relevant and the workaround solution is in fsct a solution, but it affects users directly in a non intuitive fashion. So that should be taken into consideration. The issue could be marked as solved, but personally this needs addressing if a migration from DEB to Snap is something that would want to be done in an intuitive, friendly way.
