### ISSUE TITLE
error: cannot install "steam": snap "steam" assumes unsupported features: snapd2.62

### ISSUE THREAD

**Issue by pblottiere** [canonical/steam-snap#406]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

steam cannot be installed with snap because snapd2.62 is not available in channels anymore 

### Expected Behavior

steam should be installable with snap

### Steps To Reproduce

``` console
$ snap install steam
error: cannot install "steam": snap "steam" assumes unsupported features: snapd2.62
```

### Environment

```yaml
`snap run steam.report` cannot be run because `steam` is not installed
```

### Anything else?

``` console
$ snap info snapd
name:      snapd
summary:   Daemon and tooling that enable snap packages
publisher: Canonical✓
store-url: https://snapcraft.io/snapd
contact:   https://github.com/snapcore/snapd/issues
license:   GPL-3.0
description: |
  Install, configure, refresh and remove snap packages. Snaps are
  'universal' packages that work across many different Linux systems,
  enabling secure distribution of the latest apps and utilities for
  cloud, servers, desktops and the internet of things.

  Start with 'snap list' to see installed snaps.
type:         snapd
snap-id:      PMrrV4ml8uWuEUDBT8dSGnKUYbevVhc4
tracking:     latest/stable
refresh-date: today at 23:24 CEST
channels:
  latest/stable:    2.63                  2024-05-23 (21759) 40MB -
  latest/candidate: 2.65.1                2024-09-04 (22830) 46MB -
  latest/beta:      2.65.1                2024-08-24 (22830) 46MB -
  latest/edge:      2.65.2+git92.g6d1aacd 2024-09-07 (22944) 46MB -
installed:          2.63                             (21759) 40MB snapd
```

**Comment by ashuntu** [comment]
snapd 2.62 should just be the minimum required version of snapd for Steam to be installed, so something else is likely going on. Does switching to a different channel of snapd change anything (e.g. `snap refresh snapd --candidate`)?

**Comment by sphinks** [comment]
I have the same issue with Fedora. Installed snapd version is 2.71, however if I go for steam install I get 
```
error: cannot install "steam": snap "steam" assumes unsupported features: snapd2.62
```

In snapcraft file there is a line
```
assumes:
  - snapd2.62
 ```

That looks the root cause of the issue. As far as I understand that require me to have exactly 2.62 version, however it should minimal version. Isn't it?

**Comment by ashuntu** [comment]
It should be a minimum requirement. What's the output of `snap info snapd`?

**Comment by sphinks** [comment]
@ashuntu version 2.71

<img width="879" height="638" alt="Image" src="https://github.com/user-attachments/assets/c4a59178-7a4c-4f15-981d-8a3f7dd0a2e3" />

**Comment by sphinks** [comment]
Hm! That is interesting. If I run `snap --version` I get different version output:

<img width="446" height="155" alt="Image" src="https://github.com/user-attachments/assets/ce3fb1d1-bfe9-457e-9af8-27a313d3e4f7" />

**Comment by ashuntu** [comment]
Interesting, yeah that's likely the culprit. If you have trouble updating snapd you can always try purging and reinstalling snapd as well.
