### ISSUE TITLE
Multi versus is broken

### ISSUE THREAD

**Issue by Fuseteam** [canonical/steam-snap#49]
**Describe the bug**
multiversus does not launch on a fresh install

**To Reproduce**
1. install the steam snap
2. enable steam play for unsupported titles
3. install multiversus
4. multiversus refuses to launch

**Expected behavior**
After a fresh installation, multiversus should go through a post installation process which including installing anti cheat software (EOS) and processing vulkan shaders

**Environment**  

`snap info steam`  
```
name:      steam
summary:   Launcher for the Steam software distribution service (Early Access)
publisher: Canonical✓
store-url: https://snapcraft.io/steam
contact:   https://github.com/canonical/steam-snap
license:   unset
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
commands:
  - steam
snap-id:      NeoQngJVBf2wKC48bxnF2xqmfEFGdVnx
tracking:     latest/edge
refresh-date: today at 08:47 -03
channels:
  latest/stable:    –                              
  latest/candidate: –                              
  latest/beta:      1.0.0.74 2022-07-28 (39) 371MB -
  latest/edge:      1.0.0.75 2022-10-05 (52) 365MB -
installed:          1.0.0.75            (52) 365MB -
```

`snap version`
```
snap    2.57.2
snapd   2.57.2
series  16
ubuntu  22.04
kernel  5.15.0-48-generic
```

**Comment by ashuntu** [comment]
I was able to reproduce with an NVIDIA card with the following logs:
```shell
pressure-vessel-wrap[214400]: W: "var/lib/snapd/hostfs/usr/share/drirc.d" is unlikely to appear in "/run/host"
pressure-vessel-wrap[214400]: W: Found more than one possible drirc.d data directory from provider
pressure-vessel-wrap[214400]: W: "var/lib/snapd/hostfs/usr/share/nvidia" is unlikely to appear in "/run/host"
pressure-vessel-wrap[214400]: W: "var/lib/snapd/hostfs/usr/share/nvidia" is unlikely to appear in "/run/host"
bwrap: Can't bind mount /oldroot/home on /newroot/home: Unable to mount source on destination: Permission denied
```

@Fuseteam 
Do you also have an NVIDIA card? And could you provide any warnings/errors Steam outputs when you try to run the game?

**Comment by Fuseteam** [comment]
I actually have integrated inntel graphics, i can see if i can find logs.

**Comment by ashuntu** [comment]
> I actually have integrated intel graphics, i can see if i can find logs. Both intel uhd 620 and intel xe g7

If you run steam from the terminal (e.g. `snap run steam`) it will output logs when you run the game. There may be a lot, so try to cut it down from where you actually hit 'play' and onward.

**Comment by Fuseteam** [comment]
i did just that on the xe g7 graphics:
```
Could not connect to X session manager: Could not open network socket
Could not connect to X session manager: Could not open network socket
GameAction [AppID 1818750, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
x86_64-linux-gnu-capsule-capture-libs: code 13: open "/var/cache/ldconfig/ld.so.cache": Permission denied
pressure-vessel-wrap[312455]: E: Child process exited with code 1
GameAction [AppID 1818750, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1818750, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1818750, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1818750, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1818750 -- /home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/MultiVersus/start_protected_game.exe' -allowsteam\0
Game process added : AppID 1818750 "/home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1818750 -- /home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/MultiVersus/start_protected_game.exe' -allowsteam", ProcID 312499, IP 0.0.0.0:0
chdir /home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/MultiVersus
ERROR: ld.so: object '/home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
GameAction [AppID 1818750, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1818750, ActionID 3] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 312504 != 312501, skipping destruction (fork without exec?)
x86_64-linux-gnu-capsule-capture-libs: code 13: open "/var/cache/ldconfig/ld.so.cache": Permission denied
pressure-vessel-wrap[312501]: E: Child process exited with code 1
Game process removed: AppID 1818750 "/home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1818750 -- /home/fuseteam/snap/steam/common/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/fuseteam/snap/steam/common/.local/share/Steam/steamapps/common/MultiVersus/start_protected_game.exe' -allowsteam", ProcID 312499 
ThreadGetProcessExitCode: no such process 312502
ThreadGetProcessExitCode: no such process 312501
ThreadGetProcessExitCode: no such process 312500
Uploaded AppInterfaceStats to Steam
```
I think it's the same for the intel uhd 620 graphics

**Comment by ashuntu** [comment]
I'm not sure why you're encountering the `ld.so.cache` permission error. On my integrated intel graphics, Multiversus also fails but with `terminate called after throwing an instance of 'dxvk::DxvkError'`.

Could you try snapd from edge (`snap refresh snapd --edge`), and make sure Steam is refreshed with the latest edge as well?

**Comment by ashuntu** [comment]
> I'm not sure why you're encountering the `ld.so.cache` permission error. On my integrated intel graphics, Multiversus also fails but with `terminate called after throwing an instance of 'dxvk::DxvkError'`.
> 
> Could you try snapd from edge (`snap refresh snapd --edge`), and make sure Steam is refreshed with the latest edge as well?

Could be related to #37

**Comment by Fuseteam** [comment]
sure i'll try that and report back, i'm convinced i was on the latest edge at the time, but perhaps something changed in the past 2 weeks. 
Is there anything else i could check?

**Comment by ashuntu** [comment]
It looks like you were on edge Steam (it's been updated since, too), but edge snapd may also be beneficial.

Other than that, you could [try different Proton versions](https://github.com/canonical/steam-snap/wiki/FAQ#enable-proton-individually), but I haven't had much luck there.

**Comment by Fuseteam** [comment]
Oh edge *snapd*, sorry i misread earlier; i'll try that in a bit
I'm also on proton experimental fun enough xd

**Comment by thatLeaflet** [comment]
> > I actually have integrated intel graphics, i can see if i can find logs. Both intel uhd 620 and intel xe g7
> 
> If you run steam from the terminal (e.g. `snap run steam`) it will output logs when you run the game. There may be a lot, so try to cut it down from where you actually hit 'play' and onward.

An easier way to get this information can be done with a game's launch parameter. This is the command I use: `%command% > /home/$USER/snap/steam/common/game_log 2>&1`. The path is that way to avoid any sandboxing issues. Maybe this can be added to the troubleshooting page?

**Comment by ashuntu** [comment]
> An easier way to get this information can be done with a game's launch parameter. This is the command I use: `%command% > /home/$USER/snap/steam/common/game_log 2>&1`. The path is that way to avoid any sandboxing issues. Maybe this can be added to the troubleshooting page?

Good suggestion!
https://github.com/canonical/steam-snap/wiki/Troubleshooting#game-logs

**Comment by edurojasr** [comment]
Hi!

I hit the `bwrap: Can't bind mount /oldroot/home on /newroot/home` with AMD iGPU.

`steam --edge` rev 72
`snapd --stable` 2.57.4

For all games that use Proton I got that erro. Switching to 

`steam --edge` rev 72
`snapd --edge`2.57.5+git917.ga62aa3c

Fix the `bwrap` problem. Maybe adding in the steam snap description or in the github that's its better using `snapd --edge` would help for less experience users.

Thanks for all the work, love snap steam :heart:

**Comment by edurojasr** [comment]
FYI [Multiversus is currently broken with the Steam beta](https://github.com/ValveSoftware/Proton/issues/6031#issuecomment-1287874921)

Maybe this helps
