### ISSUE TITLE
Still can not locate secondary HDD under /run/media/

### ISSUE THREAD

**Issue by AussieAnon** [canonical/steam-snap#65]
I noticed this was a previous issue but its no longer listed.

I currently use the edge version of Steam snap, when I go to add my second internal HDD, I can not add my /run/media/games mount.

I made sure I own the drive via 'sudo chown -R username /run/media/games' but its still not able to be added as the default install drive.

Any help appreciated - I really hope these secondary HDD issues can be corrected so I don't need to upgrade the entire system to 22.10 just for Mesa 22.2.x

**Comment by kenvandine** [comment]
Shouldn't this be available under /media?  I just tested with an external USB drive.  It automounts under /media/$USER/ and was available for game storage in steam.

**Comment by AussieAnon** [comment]
/smh 

Didn't try that, and it works. But now can't launch any game that uses proton. It immediately closes :(

**Comment by kenvandine** [comment]
What version of snapd do you have installed?  If you don't have snapd from the edge channel, please test that.  It would also be helpful to get console output from running steam from a terminal.
