### ISSUE TITLE
Controller configuration window shows no text

### ISSUE THREAD

**Issue by cse84** [canonical/steam-snap#69]
I ran `snap install --beta steam` on Ubuntu 19.10 and got 1.0.0.75. When I clicked View->Settings->Controller->General Controller Settings in Steam, the configuration window appeared, but no text was visible on any window, button etc., making controller configuration impossible. Then i uninstalled the snap and ran `apt-get install steam` and got 1.0.0.54. In the .deb-version of Steam the controller settings worked perfectly and I could control big picture mode with my lovely Playstation 3 controller.

Not sure if it is related, but although the controller worked in Steam itself, I could not yet find a Steam game that recognized my controller (but this may be due to my lack of experience with Steam - I might not have found the right button to click for activating controller input). My controller **is** recognized and works perfectly in mupen64plus (installed via APT), so controller input works in principle.

**Environment**  

`snap version`
```
snap    2.57.4
snapd   2.57.4
series  16
ubuntu  19.10
kernel  5.3.0-64-generic
```

Distro & version:  Ubuntu 19.10
CPU:  core i7-8700K
GPU:  Geforce RTX 2060 Super
GPU Driver Version:  official nvidia driver version 435.21

**Comment by ashuntu** [comment]
The configuration issue is related to #5 and is being worked on. I was able to use my Steam controller in a game, so I'm unsure what's happening for you.

**Comment by ZoopOTheGoop** [comment]
The controller issues are blocked on snapd resolving some `udev` issues, which is on the roadmap, but controllers/steam input are unlikely to work until then, though there may be exceptions.

**Comment by kenvandine** [comment]
As a workaround to get steam-devices support, you can install that as a deb without including recommends.

`sudo apt install --no-install-recommends steam-devices`

**Comment by mhalano** [comment]
@cse84 Could you test the latest versions? #5 was already fixed

**Comment by ashuntu** [comment]
This should be resolved, please reopen if not.
