### ISSUE TITLE
The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.515.65.01'.  This library is required at run time.

### ISSUE THREAD

**Issue by shithedark** [canonical/steam-snap#70]
Running games under Nvidia produces the error : The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.515.65.01'.  This library is required at run time.

To reproduce : 
1- Switch to Nvidia drivers.
2- snap run steam from terminal.
3- click on a game (in my case Dota 2) and observe
Steps to reproduce the behavior as the game launches but doesn't produce any graphics and the following error appears in the termianl :  The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.515.65.01'.  This library is required at run time.

Expected Behavior : The game should run.

**Screenshots**

**Environment**  

`snap info steam`  
```
name:      steam
summary:   Launcher for the Steam software distribution service (Early Access)
publisher: Canonical✓
store-url: https://snapcraft.io/steam
contact:   https://github.com/canonical/steam-snap
license:   unset
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
commands:
  - steam.report
  - steam
snap-id:      NeoQngJVBf2wKC48bxnF2xqmfEFGdVnx
tracking:     latest/edge
refresh-date: 2 days ago, at 18:04 EEST
channels:
  latest/stable:    –                              
  latest/candidate: –                              
  latest/beta:      1.0.0.75 2022-10-07 (52) 365MB -
  latest/edge:      1.0.0.75 2022-10-19 (70) 378MB -
installed:          1.0.0.75            (70) 378MB -

```

`snap version`
```
snap    2.57.5+git853.g2e347b2
snapd   2.57.5+git853.g2e347b2
series  16
ubuntu  22.10
kernel  5.19.0-21-generic

```

Distro & version:  Ubuntu 22.10
CPU:  Intel® Core™ i7-8550U × 8
GPU:  NVIDIA GeForce MX110
GPU Driver Version:  NVIDIA-SMI 515.65.01    Driver Version: 515.65.01

**Logs**
The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.515.65.01'.  This library is required at run time.

**Comment by ashuntu** [comment]
This is a known problem and we're looking into it :).

**Comment by shithedark** [comment]
@ashuntu sadly the problem is still occuring even tho i am on the edge channels.

**Comment by TyraelTLK** [comment]
Hi, I have the same problem but with a different nvidia version and trying to run Alien Swarm: Reactive Drop:

`The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.515.105.01'.  This library is required at run time.`

snap info steam

```
name:      steam
summary:   Launcher for the Steam software distribution service (Early Access)
publisher: Canonical✓
store-url: https://snapcraft.io/steam
contact:   https://github.com/canonical/steam-snap
license:   unset
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
commands:
  - steam.report
  - steam
snap-id:      NeoQngJVBf2wKC48bxnF2xqmfEFGdVnx
tracking:     latest/beta
refresh-date: 2023-01-14
channels:
  latest/stable:    1.0.0.75 2023-04-17 (136) 188MB -
  latest/candidate: 1.0.0.75 2023-04-06 (136) 188MB -
  latest/beta:      1.0.0.75 2022-12-05  (83) 388MB -
  latest/edge:      1.0.0.76 2023-04-13 (137) 188MB -
installed:          1.0.0.75             (83) 388MB -
```

snap version
```
snap    2.59.1
snapd   2.59.1
series  16
ubuntu  22.10
kernel  5.19.0-40-generic
```

**Comment by ashuntu** [comment]
Try installing the 32-bit NVIDIA drivers as described here: https://github.com/canonical/steam-snap/wiki/FAQ#32-bit-driver

**Comment by ashuntu** [comment]
I'm going to close this due to inactivity. I'd imagine this is related to https://github.com/canonical/steam-snap/issues/311.

In any case, make sure you have 32-bit NVIDIA drivers installed as well as the normal 64-bit drivers. If this is still an issue, you can try working around it by running `sudo /usr/lib/snapd/snap-discard-ns steam` from a terminal or rebooting your system.
