### ISSUE TITLE
No access to games installed with .deb Steam

### ISSUE THREAD

**Issue by mhalano** [canonical/steam-snap#8]
I checked, and Snap Steam has a plug for `~/.local/share/Steam` and `~/Steam` directories using the `personal-files` interface. I think this would be allowed to Steam open up using the configuration and games from one of these directories, but this isn't happening. So, this is both a question, what should happen with this interface, and a bug report if the intent is to read and write in these pre-existent directories.

**Comment by kenvandine** [comment]
We have a migration script that will migrate your library automatically on first launch, but disabled it during the early access until we get more testing.  When this is ready for release, we will enable the migration.
