### ISSUE TITLE
Steam library folder in /mnt unable to be added (must be on a filesystem mounted with execute permissions)

### ISSUE THREAD

**Issue by Nightmayr** [canonical/steam-snap#9]
Using the steam snap (edge channel revision 8) with the removable-media plug connected, attempting to add a Steam library from an SSD mounted at /mnt results in the following message:
![image](https://user-images.githubusercontent.com/24817147/166321132-a9be86ee-c966-421b-bb9b-0e5988e49b74.png)

**Comment by ilvipero** [comment]
I can reproduce this issue on my desktop. I get the exact same error when trying to add Steam library from a lvm device mounted under /mnt. 
My fstab looks good, can't spot obvious issues there. Also, .deb version of Steam can add library from same device on same mountpoint.

**Comment by mlacunza** [comment]
Same issue here in Ubuntu 22.04, using the Steam original software I can install games in the mounted HD

**Comment by jhenstridge** [comment]
The AppArmor rules added by the removable-media interface include:

```
# Allow write access to anything under /mnt
/mnt/** rwkl,
```

That is, it allows read, write, lock, and link access to files under `/mnt/`. Absent from that list is execute permission, leading to the error in question.

So we either need to change the removable-media interface to add the execute permission, or maybe make the permission opt-in via an interface attribute.

**Comment by stevewallin** [comment]
same issue here - extending James comment to include the link to the snapd source link https://github.com/snapcore/snapd/blob/master/interfaces/builtin/removable_media.go

**Comment by Dadadah** [comment]
I'm able to use /mnt in the latest version of snap including the PR above.

**Comment by ilvipero** [comment]
Works fine for me too after this change. I can add my steam library that is under /mnt . Thanks!
