### ISSUE TITLE
Crash at startup on CentOS 7 

### ISSUE THREAD

**Issue by KnightOfCups** [canonical/steam-snap#90]
**Describe the bug**
While having issue with a PS3 controller not detected under Steam from Flatpak, I try to install the snap version to check if the problem is also present.
Even on the edge or the beta channel, Steam client failed from the very first execution.

**To Reproduce**
From an up-to-date CentOS 7 workstation with a ongoing Snap installation
1. Switch to beta channel for `snapd`
2. Install beta/edge version of Steam
```
INFO snap "steam" has bad plugs or slots: steam-support (unknown interface "steam-support")
INFO snap "steam" has bad plugs or slots: steam-support (unknown interface "steam-support")
```
3. Launch the client via `/snap/bin/steam` or `snap run steam`

I was able to reproduce the behavior on fresh CentOS 7 VM install.

**Environment**
Not being able to generate a report with `steam.report`
```
This script relies on the system-observe Snap plug.
Outside of the snap, run `snap connect steam:system-observe`.
```

**Logs**
```
(zenity:22546): GLib-ERROR **: 19:25:52.920: file ../../../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'
/snap/steam/86/usr/lib/steam/bin_steam.sh: line 205: 22546 Trace/breakpoint trap   (core dumped) zenity --question --text="Couldn't find Steam content, did you move it?" --ok-label="Search" --cancel-label="Reinstall"
bin_steam.sh[22498]: Setting up Steam content in .../.snap/data/steam/common/.local/share/Steam
/snap/steam/86/usr/lib/steam/bin_steam.sh: line 27: 22560 Trace/breakpoint trap   (core dumped) zenity "$style" --text="$*" 2> /dev/null
Warning: Tried to connect to session manager, None of the authentication protocols specified are supported
Couldn't set up Steam data - please contact technical support
Press enter to continue:
```

**Comment by ZoopOTheGoop** [comment]
Turns out Core22 is currently not working on CentOS due to some kernel features it uses:

**Comment by KnightOfCups** [comment]
As advised on https://github.com/snapcrafters/signal-desktop/issues/76#issuecomment-1396211715, I upgraded the version of libseccomp (2.3.1 system -> 2.4.4 builded).
After updating, Steam is running now (still graphics issues  but unrelated)

**Comment by KnightOfCups** [comment]
As advised on https://github.com/snapcrafters/signal-desktop/issues/76#issuecomment-1396211715, I upgraded the version of libseccomp (2.3.1 system -> 2.4.4 builded).
After updating, Steam is running now (still graphics issues  but unrelated)
